{
    "type": "error",
    "data": "Entity Extraction Error",
    "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 122, in __call__\n    result = await self._process_document(text, prompt_variables)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 161, in _process_document\n    response = await self._llm(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\json_parsing_llm.py\", line 34, in __call__\n    result = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\openai_token_replacing_llm.py\", line 37, in __call__\n    return await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\openai_history_tracking_llm.py\", line 33, in __call__\n    output = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\caching_llm.py\", line 96, in __call__\n    result = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 177, in __call__\n    result, start = await execute_with_retry()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 159, in execute_with_retry\n    async for attempt in retryer:\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 166, in __anext__\n    do = await self.iter(retry_state=self._retry_state)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 153, in iter\n    result = await action(retry_state)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\_utils.py\", line 99, in inner\n    return call(*args, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\__init__.py\", line 418, in exc_check\n    raise retry_exc.reraise()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\__init__.py\", line 185, in reraise\n    raise self.last_attempt.result()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\concurrent\\futures\\_base.py\", line 451, in result\n    return self.__get_result()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\concurrent\\futures\\_base.py\", line 403, in __get_result\n    raise self._exception\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 165, in execute_with_retry\n    return await do_attempt(), start\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 151, in do_attempt\n    await sleep_for(sleep_time)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 147, in do_attempt\n    return await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 50, in __call__\n    return await self._invoke(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 54, in _invoke\n    output = await self._execute_llm(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\openai_chat_llm.py\", line 53, in _execute_llm\n    completion = await self.client.chat.completions.create(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\resources\\chat\\completions.py\", line 1633, in create\n    return await self._post(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\_base_client.py\", line 1838, in post\n    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\_base_client.py\", line 1532, in request\n    return await self._request(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\_base_client.py\", line 1633, in _request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 194112, Requested 7584. Please try again in 508ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}\n",
    "source": "Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 194112, Requested 7584. Please try again in 508ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}",
    "details": {
        "doc_index": 0,
        "text": "next lamp flickered into darkness. Twelve times\nhe clicked the Put-Outer, until the only lights left on the whole street\nwere two tiny pinpricks in the distance, which were the eyes of the cat\nwatching him. If anyone looked out of their window now, even beady-eyed\nMrs. Dursley, they wouldn't be able to see anything that was happening\ndown on the pavement. Dumbledore slipped the Put-Outer back inside his\ncloak and set off down the street toward number four, where he sat down\non the wall next to the cat. He didn't look at it, but after a moment he\nspoke to it.\n\n\"Fancy seeing you here, Professor McGonagall.\"\n\nHe turned to smile at the tabby, but it had gone. Instead he was smiling\nat a rather severe-looking woman who was wearing square glasses exactly\nthe shape of the markings the cat had had around its eyes. She, too, was\nwearing a cloak, an emerald one. Her black hair was drawn into a tight\nbun. She looked distinctly ruffled.\n\n\"How did you know it was me?\" she asked.\n\n\"My dear Professor, I 've never seen a cat sit so stiffly.\"\n\n\"You'd be stiff if you'd been sitting on a brick wall all day,\" said\nProfessor McGonagall.\n\n\"All day? When you could have been celebrating? I must have passed a\ndozen feasts and parties on my way here.\"\n\nProfessor McGonagall sniffed angrily.\n\n\"Oh yes, everyone's celebrating, all right,\" she said impatiently.\n\"You'd think they'd be a bit more careful, but no -- even the Muggles\nhave noticed something's going on. It was on their news.\" She jerked her\nhead back at the Dursleys' dark living-room window. \"I heard it. Flocks\nof owls... shooting stars.... Well, they're not completely stupid. They\nwere bound to notice something. Shooting stars down in Kent -- I'll bet\nthat was Dedalus Diggle. He never had much sense.\"\n\n\"You can't blame them,\" said Dumbledore gently. \"We've had precious\nlittle to celebrate for eleven years.\"\n\n\"I know that,\" said Professor McGonagall irritably. \"But that's no\nreason to lose our heads. People are being downright careless, out on\nthe streets in broad daylight, not even dressed in Muggle clothes,\nswapping rumors.\"\n\nShe threw a sharp, sideways glance at Dumbledore here, as though hoping\nhe was going to tell her something, but he didn't, so she went on. \"A\nfine thing it would be if, on the very day YouKnow-Who seems to have\ndisappeared at last, the Muggles found out about us all. I suppose he\nreally has gone, Dumbledore?\"\n\n\"It certainly seems so,\" said Dumbledore. \"We have much to be thankful\nfor. Would you care for a lemon drop?\"\n\n\"A what?\"\n\n\"A lemon drop. They're a kind of Muggle sweet I'm rather fond of\"\n\n\"No, thank you,\" said Professor McGonagall coldly, as though she didn't\nthink this was the moment for lemon drops. \"As I say, even if\nYou-Know-Who has gone -\"\n\n\"My dear Professor, surely a sensible person like yourself can call him\nby his name? All this 'You- Know-Who' nonsense -- for eleven years I\nhave been trying to persuade people to call him by his proper name:\nVoldemort.\" Professor McGonagall flinched, but Dumbledore, who was\nunsticking two lemon drops, seemed not to notice. \"It all gets so\nconfusing if we keep saying 'You-Know-Who.' I have never seen any reason\nto be frightened of saying Voldemort's name.\n\n\"I know you haven 't, said Professor McGonagall, sounding half\nexasperated, half admiring. \"But you're different. Everyone knows you're\nthe only one You-Know- oh, all right, Voldemort, was frightened of.\"\n\n\"You flatter me,\" said Dumbledore calmly. \"Voldemort had powers I will\nnever have.\"\n\n\"Only because you're too -- well -- noble to use them.\"\n\n\"It's lucky it's dark. I haven't blushed so much since Madam Pomfrey\ntold me she liked my new earmuffs.\"\n\nProfessor McGonagall shot a sharp look at Dumbledore and said, \"The owls\nare nothing next to the rumors that are flying around. You know what\neveryone's saying? About why he's disappeared? About what finally\nstopped him?\"\n\nIt seemed that Professor McGonagall had reached the point she was most\nanxious to discuss, the real reason she had been waiting on a cold, hard\nwall all day, for neither as a cat nor as a woman had she fixed\nDumbledore with such a piercing stare as she did now. It was plain that\nwhatever \"everyone\" was saying, she was not going to believe it until\nDumbledore told her it was true. Dumbledore, however, was choosing\nanother lemon drop and did not answer.\n\n\"What they're saying,\" she pressed on, \"is that last night Voldemort\nturned up in Godric's Hollow. He went to find the Potters. The rumor is\nthat Lily and James Potter are -- are -- that they're -- dead. \"\n\nDumbledore bowed his head. Professor McGonagall gasped.\n\n\"Lily and James... I can't believe it... I didn't want to believe it...\nOh, Albus...\"\n\nDumbledore reached out and patted her on the shoulder. \"I know... I\nknow...\" he said heavily.\n\nProfessor McGonagall's voice trembled as she went"
    }
}
{
    "type": "error",
    "data": "Entity Extraction Error",
    "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 122, in __call__\n    result = await self._process_document(text, prompt_variables)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 161, in _process_document\n    response = await self._llm(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\json_parsing_llm.py\", line 34, in __call__\n    result = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\openai_token_replacing_llm.py\", line 37, in __call__\n    return await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\openai_history_tracking_llm.py\", line 33, in __call__\n    output = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\caching_llm.py\", line 96, in __call__\n    result = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 177, in __call__\n    result, start = await execute_with_retry()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 159, in execute_with_retry\n    async for attempt in retryer:\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 166, in __anext__\n    do = await self.iter(retry_state=self._retry_state)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 153, in iter\n    result = await action(retry_state)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\_utils.py\", line 99, in inner\n    return call(*args, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\__init__.py\", line 418, in exc_check\n    raise retry_exc.reraise()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\__init__.py\", line 185, in reraise\n    raise self.last_attempt.result()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\concurrent\\futures\\_base.py\", line 451, in result\n    return self.__get_result()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\concurrent\\futures\\_base.py\", line 403, in __get_result\n    raise self._exception\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 165, in execute_with_retry\n    return await do_attempt(), start\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 151, in do_attempt\n    await sleep_for(sleep_time)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 147, in do_attempt\n    return await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 50, in __call__\n    return await self._invoke(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 54, in _invoke\n    output = await self._execute_llm(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\openai_chat_llm.py\", line 53, in _execute_llm\n    completion = await self.client.chat.completions.create(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\resources\\chat\\completions.py\", line 1633, in create\n    return await self._post(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\_base_client.py\", line 1838, in post\n    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\_base_client.py\", line 1532, in request\n    return await self._request(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\_base_client.py\", line 1633, in _request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 198452, Requested 7730. Please try again in 1.854s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}\n",
    "source": "Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 198452, Requested 7730. Please try again in 1.854s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}",
    "details": {
        "doc_index": 0,
        "text": "almost flew, back down the corridor. Filch must have hurried off to look\nfor them somewhere else, because they didn't see him anywhere, but they\nhardly cared -- all they wanted to do was put as much space as possible\nbetween them and that monster. They didn't stop running until they\nreached the portrait of the Fat Lady on the seventh floor.\n\n\"Where on earth have you all been?\" she asked, looking at their\nbathrobes hanging off their shoulders and their flushed, sweaty faces.\n\n\"Never mind that -- pig snout, pig snout,\" panted Harry, and the\nportrait swung forward. They scrambled into the common room and\ncollapsed, trembling, into armchairs.\n\nIt was a while before any of them said anything. Neville, indeed, looked\nas if he'd never speak again.\n\n\"What do they think they're doing, keeping a thing like that locked up\nin a school?\" said Ron finally. \"If any dog needs exercise, that one\ndoes.\"\n\nHermione had got both her breath and her bad temper back again. \"You\ndon't use your eyes, any of you, do you?\" she snapped. \"Didn't you see\nwhat it was standing on.\n\n\"The floor?\" Harry suggested. \"I wasn't looking at its feet, I was too\nbusy with its heads.\"\n\n\"No, not the floor. It was standing on a trapdoor. It's obviously\nguarding something.\"\n\nShe stood up, glaring at them.\n\nI hope you're pleased with yourselves. We could all have been killed --\nor worse, expelled. Now, if you don't mind, I'm going to bed.\"\n\nRon stared after her, his mouth open.\n\n\"No, we don't mind,\" he said. \"You'd think we dragged her along,\nwouldn't you.\n\nBut Hermione had given Harry something else to think about as he climbed\nback into bed. The dog was guarding something.... What had Hagrid said?\nGringotts was the safest place in the world for something you wanted to\nhide -- except perhaps Hogwarts.\n\nIt looked as though Harry had found out where the grubby littie package\nfrom vault seven hundred and thirteen was.\n\n\nCHAPTER TEN\n\nHALLOWEEN\n\nMalfoy couldn't believe his eyes when he saw that Harry and Ron were\nstill at Hogwarts the next day, looking tired but perfectly cheerful.\nIndeed, by the next morning Harry and Ron thought that meeting the\nthree-headed dog had been an excellent adventure, and they were quite\nkeen to have another one. In the meantime, Harry filled Ron in about the\npackage that seemed to have been moved from Gringotts to Hogwarts, and\nthey spent a lot of time wondering what could possibly need such heavy\nprotection. \"It's either really valuable or really dangerous,\" said Ron.\n\"Or both,\" said Harry.\n\n\nBut as all they knew for sure about the mysterious object was that it\nwas about two inches long, they didn't have much chance of guessing what\nit was without further clues.\n\nNeither Neville nor Hermione showed the slightest interest in what lay\nunderneath the dog and the trapdoor. All Neville cared about was never\ngoing near the dog again.\n\nHermione was now refusing to speak to Harry and Ron, but she was such a\nbossy know-it-all that they saw this as an added bonus. All they really\nwanted now was a way of getting back at Malfoy, and to their great\ndelight, just such a thing arrived in the mail about a week later.\n\nAs the owls flooded into the Great Hall as usual, everyone's attention\nwas caught at once by a long, thin package carried by six large screech\nowls. Harry was just as interested as everyone else to see what was in\nthis large parcel, and was amazed when the owls soared down and dropped\nit right in front of him, knocking his bacon to the floor. They had\nhardly fluttered out of the way when another owl dropped a letter on top\nof the parcel.\n\nHarry ripped open the letter first, which was lucky, because it said:\n\n\nDO NOT OPEN THE PARCEL AT THE TABLE.\n\nIt contains your new Nimbus Two Thousand, but I don't want everybody\nknowing you've got a broomstick or they'll all want one. Oliver Wood\nwill meet you tonight on the Quidditch field at seven o'clock for your\nfirst training session.\n\nProfessor McGonagall\n\nHarry had difficulty hiding his glee as he handed the note to Ron to\nread.\n\n\"A Nimbus Two Thousand!\" Ron moaned enviously. \"I've never even touched\none.\"\n\nThey left the hall quickly, wanting to unwrap the broomstick in private\nbefore their first class, but halfway across the entrance hall they\nfound the way upstairs barred by Crabbe and Goyle. Malfoy seized the\npackage from Harry and felt it.\n\n\"That's a broomstick,\" he said, throwing it back to Harry with a mixture\nof jealousy and spite on his face. \"You'll be in for it this time,\nPotter, first years aren't allowed them.\"\n\nRon couldn't resist it.\n\n\"It's not any old broomstick,\" he said, \"it's a Nimbus Two Thousand.\nWhat did you say you've got at home, Malfoy, a Comet Two Sixty?\" Ron\ngrinned at Harry. \"Comets look flashy, but they're not in the same\nleague as the Nimbus.\"\n\n\"What would you know about it, Weasley, you couldn't afford half the\nhandle,\" Malfoy snapped back. \"I suppose you and your brothers have to\nsave up twig by twig.\"\n\nBefore Ron could answer, Professor Flitwick appeared at Malfoy's elbow.\n\n\"Not arguing, I hope, boys?\" he squeaked.\n\n\"Pot"
    }
}
{
    "type": "error",
    "data": "Entity Extraction Error",
    "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 122, in __call__\n    result = await self._process_document(text, prompt_variables)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 150, in _process_document\n    response = await self._llm(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\json_parsing_llm.py\", line 34, in __call__\n    result = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\openai_token_replacing_llm.py\", line 37, in __call__\n    return await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\openai_history_tracking_llm.py\", line 33, in __call__\n    output = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\caching_llm.py\", line 96, in __call__\n    result = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 177, in __call__\n    result, start = await execute_with_retry()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 159, in execute_with_retry\n    async for attempt in retryer:\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 166, in __anext__\n    do = await self.iter(retry_state=self._retry_state)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 153, in iter\n    result = await action(retry_state)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\_utils.py\", line 99, in inner\n    return call(*args, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\__init__.py\", line 418, in exc_check\n    raise retry_exc.reraise()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\__init__.py\", line 185, in reraise\n    raise self.last_attempt.result()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\concurrent\\futures\\_base.py\", line 451, in result\n    return self.__get_result()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\concurrent\\futures\\_base.py\", line 403, in __get_result\n    raise self._exception\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 165, in execute_with_retry\n    return await do_attempt(), start\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 151, in do_attempt\n    await sleep_for(sleep_time)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 147, in do_attempt\n    return await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 50, in __call__\n    return await self._invoke(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 54, in _invoke\n    output = await self._execute_llm(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\openai_chat_llm.py\", line 53, in _execute_llm\n    completion = await self.client.chat.completions.create(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\resources\\chat\\completions.py\", line 1633, in create\n    return await self._post(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\_base_client.py\", line 1838, in post\n    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\_base_client.py\", line 1532, in request\n    return await self._request(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\_base_client.py\", line 1633, in _request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 194347, Requested 6862. Please try again in 362ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}\n",
    "source": "Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 194347, Requested 6862. Please try again in 362ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}",
    "details": {
        "doc_index": 0,
        "text": "'t\ngoing at all the way he wanted.\n\n\"Like this,\" he said irritably. He seized his left ear and pulled. His\nwhole head swung off his neck and fell onto his shoulder as if it was on\na hinge. Someone had obviously tried to behead him, but not done it\nproperly. Looking pleased at the stunned looks on their faces, Nearly\nHeadless Nick flipped his head back onto his neck, coughed, and said,\n\"So -- new Gryffindors! I hope you're going to help us win the house\nchampionship this year? Gryffindors have never gone so long without\nwinning. Slytherins have got the cup six years in a row! The Bloody\nBaron's becoming almost unbearable -- he's the Slytherin ghost.\"\n\nHarry looked over at the Slytherin table and saw a horrible ghost\nsitting there, with blank staring eyes, a gaunt face, and robes stained\nwith silver blood. He was right next to Malfoy who, Harry was pleased to\nsee, didn't look too pleased with the seating arrangements.\n\n\"How did he get covered in blood?\" asked Seamus with great interest.\n\n\"I've never asked,\" said Nearly Headless Nick delicately.\n\nWhen everyone had eaten as much as they could, the remains of the food\nfaded from the plates, leaving them sparkling clean as before. A moment\nlater the desserts appeared. Blocks of ice cream in every flavor you\ncould think of, apple pies, treacle tarts, chocolate eclairs and jam\ndoughnuts, trifle, strawberries, Jell-O, rice pudding -- \"\n\nAs Harry helped himself to a treacle tart, the talk turned to their\nfamilies.\n\n\"I'm half-and-half,\" said Seamus. \"Me dad's a Muggle. Mom didn't tell\nhim she was a witch 'til after they were married. Bit of a nasty shock\nfor him.\"\n\nThe others laughed.\n\n\"What about you, Neville?\" said Ron.\n\n\"Well, my gran brought me up and she's a witch,\" said Neville, \"but the\nfamily thought I was all- Muggle for ages. My Great Uncle Algie kept\ntrying to catch me off my guard and force some magic out of me -- he\npushed me off the end of Blackpool pier once, I nearly drowned -- but\nnothing happened until I was eight. Great Uncle Algie came round for\ndinner, and he was hanging me out of an upstairs window by the ankles\nwhen my Great Auntie Enid offered him a meringue and he accidentally let\ngo. But I bounced -- all the way down the garden and into the road. They\nwere all really pleased, Gran was crying, she was so happy. And you\nshould have seen their faces when I got in here -- they thought I might\nnot be magic enough to come, you see. Great Uncle Algie was so pleased\nhe bought me my toad.\"\n\nOn Harry's other side, Percy Weasley and Hermione were talking about\nlessons (\"I do hope they start right away, there's so much to learn, I'm\nparticularly interested in Transfiguration, you know, turning something\ninto something else, of course, it's supposed to be very difficult-\";\n\"You'll be starting small, just matches into needles and that sort of\nthing -- \").\n\nHarry, who was starting to feel warm and sleepy, looked up at\n\nthe High Table again. Hagrid was drinking deeply from his goblet.\nProfessor McGonagall was talking to Professor Dumbledore. Professor\nQuirrell, in his absurd turban, was talking to a teacher with greasy\nblack hair, a hooked nose, and sallow skin.\n\nIt happened very suddenly. The hook-nosed teacher looked past Quirrell's\nturban straight into Harry's eyes -- and a sharp, hot pain shot across\nthe scar on Harry's forehead.\n\n\"Ouch!\" Harry clapped a hand to his head.\n\n\"What is it?\" asked Percy.\n\n\"N-nothing.\"\n\nThe pain had gone as quickly as it had come. Harder to shake off was the\nfeeling Harry had gotten from the teacher's look -- a feeling that he\ndidn't like Harry at all.\n\n\"Who's that teacher talking to Professor Quirrell?\" he asked Percy.\n\n\"Oh, you know Quirrell already, do you? No wonder he's looking so\nnervous, that's Professor Snape. He teaches Potions, but he doesn't want\nto -- everyone knows he's after Quirrell's job. Knows an awful lot about\nthe Dark Arts, Snape.\"\n\nHarry watched Snape for a while, but Snape didn't look at him again.\n\nAt last, the desserts too disappeared, and Professor Dumbledore got to\nhis feet again. The hall fell silent.\n\n\"Ahern -- just a few more words now that we are all fed and watered. I\nhave a few start-of-term notices to give you.\n\n\"First years should note that the forest on the grounds is forbidden to\nall pupils. And a few of our older students would do well to remember\nthat as well.\"\n\nDumbledore's twinkling eyes flashed in the direction of the Weasley\ntwins.\n\n\"I have also been asked by Mr. Filch, the caretaker, to remind you all\nthat no magic should be used between classes in the corridors.\n\n\"Quidditch trials will be held in the second week of the term. Anyone\ninterested in playing for their house teams should contact Madam Hooch.\n\n\"And finally, I must tell you that this year, the third-floor corridor\non the right-hand side is out of bounds to everyone who does not wish to\ndie a very painful death.\"\n\nHarry laughed, but he was one of the few who did.\n\n\"He"
    }
}
{
    "type": "error",
    "data": "Entity Extraction Error",
    "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 122, in __call__\n    result = await self._process_document(text, prompt_variables)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 161, in _process_document\n    response = await self._llm(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\json_parsing_llm.py\", line 34, in __call__\n    result = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\openai_token_replacing_llm.py\", line 37, in __call__\n    return await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\openai_history_tracking_llm.py\", line 33, in __call__\n    output = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\caching_llm.py\", line 96, in __call__\n    result = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 177, in __call__\n    result, start = await execute_with_retry()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 159, in execute_with_retry\n    async for attempt in retryer:\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 166, in __anext__\n    do = await self.iter(retry_state=self._retry_state)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 153, in iter\n    result = await action(retry_state)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\_utils.py\", line 99, in inner\n    return call(*args, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\__init__.py\", line 418, in exc_check\n    raise retry_exc.reraise()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\__init__.py\", line 185, in reraise\n    raise self.last_attempt.result()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\concurrent\\futures\\_base.py\", line 451, in result\n    return self.__get_result()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\concurrent\\futures\\_base.py\", line 403, in __get_result\n    raise self._exception\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 165, in execute_with_retry\n    return await do_attempt(), start\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 151, in do_attempt\n    await sleep_for(sleep_time)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 147, in do_attempt\n    return await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 50, in __call__\n    return await self._invoke(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 54, in _invoke\n    output = await self._execute_llm(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\openai_chat_llm.py\", line 53, in _execute_llm\n    completion = await self.client.chat.completions.create(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\resources\\chat\\completions.py\", line 1633, in create\n    return await self._post(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\_base_client.py\", line 1838, in post\n    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\_base_client.py\", line 1532, in request\n    return await self._request(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\_base_client.py\", line 1633, in _request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 197268, Requested 7608. Please try again in 1.462s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}\n",
    "source": "Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 197268, Requested 7608. Please try again in 1.462s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}",
    "details": {
        "doc_index": 0,
        "text": "That's another\npoint you've lost for Gryffindor.\"\n\nThis was so unfair that Harry opened his mouth to argue, but Ron kicked\nhim behind their cauldron.\n\n\"Doi* push it,\" he muttered, \"I've heard Snape can turn very nasty.\"\n\nAs they climbed the steps out of the dungeon an hour later, Harry's mind\nwas racing and his spirits were low. He'd lost two points for Gryffindor\nin his very first week -- why did Snape hate him so much? \"Cheer up,\"\nsaid Ron, \"Snape's always taking points off Fred and George. Can I come\nand meet Hagrid with you?\"\n\nAt five to three they left the castle and made their way across the\ngrounds. Hagrid lived in a small wooden house on the edge of the\nforbidden forest. A crossbow and a pair of galoshes were outside the\nfront door.\n\nWhen Harry knocked they heard a frantic scrabbling from inside and\nseveral booming barks. Then Hagrid's voice rang out, saying, \"Back, Fang\n-- back.\"\n\nHagrid's big, hairy face appeared in the crack as he pulled the door\nopen.\n\n\"Hang on,\" he said. \"Back, Fang.\"\n\nHe let them in, struggling to keep a hold on the collar of an enormous\nblack boarhound.\n\nThere was only one room inside. Hams and pheasants were hanging from the\nceiling, a copper kettle was boiling on the open fire, and in the corner\nstood a massive bed with a patchwork quilt over it.\n\n\"Make yerselves at home,\" said Hagrid, letting go of Fang, who bounded\nstraight at Ron and started licking his ears. Like Hagrid, Fang was\nclearly not as fierce as he looked.\n\n\"This is Ron,\" Harry told Hagrid, who was pouring boiling water into a\nlarge teapot and putting rock cakes onto a plate.\n\n\"Another Weasley, eh?\" said Hagrid, glancing at Ron's freckles. I spent\nhalf me life chasin' yer twin brothers away from the forest.\"\n\nThe rock cakes were shapeless lumps with raisins that almost broke their\nteeth, but Harry and Ron pretended to be enjoying them as they told\nHagrid all about their first -lessons. Fang rested his head on Harry's\nknee and drooled all over his robes.\n\nHarry and Ron were delighted to hear Hagrid call Fitch \"that old git.\"\n\n\"An' as fer that cat, Mrs. Norris, I'd like ter introduce her to Fang\nsometime. D'yeh know, every time I go up ter the school, she follows me\neverywhere? Can't get rid of her -- Fitch puts her up to it.\"\n\nHarry told Hagrid about Snape's lesson. Hagrid, like Ron, told Harry not\nto worry about it, that Snape liked hardly any of the students.\n\n\"But he seemed to really hate me.\"\n\n\"Rubbish!\" said Hagrid. \"Why should he?\"\n\nYet Harry couldn't help thinking that Hagrid didn't quite meet his eyes\nwhen he said that.\n\n\"How's yer brother Charlie?\" Hagrid asked Ron. \"I liked him a lot --\ngreat with animals.\"\n\nHarry wondered if Hagrid had changed the subject on purpose. While Ron\ntold Hagrid all about Charlie's work with dragons, Harry picked up a\npiece of paper that was lying on the table under the tea cozy. It was a\ncutting from the Daily Prophet:\n\nGRINGOTTS BREAK-IN LATEST\n\nInvestigations continue into the break-in at Gringotts on 31 July,\nwidely believed to be the work of Dark wizards or witches unknown.\n\nGringotts goblins today insisted that nothing had been taken. The vault\nthat was searched had in fact been emptied the same day.\n\n\"But we're not telling you what was in there, so keep your noses out if\nyou know what's good for you,\" said a Gringotts spokesgoblin this\nafternoon.\n\nHarry remembered Ron telling him on the train that someone had tried to\nrob Gringotts, but Ron hadn't mentioned the date.\n\n\"Hagrid!\" said Harry, \"that Gringotts break-in happened on my birthday!\nIt might've been happening while we were there!\"\n\nThere was no doubt about it, Hagrid definitely didn't meet Harry's eyes\nthis time. He grunted and offered him another rock cake. Harry read the\nstory again. The vault that was searched had in fact been emptied\nearlier that same day. Hagrid had emptied vault seven hundred and\nthirteen, if you could call it emptying, taking out that grubby little\npackage. Had that been what the thieves were looking for?\n\nAs Harry and Ron walked back to the castle for dinner, their pockets\nweighed down with rock cakes they'd been too polite to refuse, Harry\nthought that none of the lessons he'd had so far had given him as much\nto think about as tea with Hagrid. Had Hagrid collected that package\njust in time? Where was it now? And did Hagrid know something about\nSnape that he didn't want to tell Harry?\n\n\nCHAPTER NINE\n\nTHE MIDNIGHT DUEL\n\nHarry had never believed he would meet a boy he hated more than Dudley,\nbut that was before he met Draco Malfoy.\tStill, first-year\nGryffindors only had Potions with the Slytherins, so they didn't have to\nput up with Malfoy much. Or at least, they didn't until they spotted a\nnotice pinned up in the Gryffindor common room that made them all groan.\nFlying lessons would be starting on Thursday -- and Gryffindor and\nSlytherin\twould be"
    }
}
{
    "type": "error",
    "data": "Entity Extraction Error",
    "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 122, in __call__\n    result = await self._process_document(text, prompt_variables)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 161, in _process_document\n    response = await self._llm(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\json_parsing_llm.py\", line 34, in __call__\n    result = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\openai_token_replacing_llm.py\", line 37, in __call__\n    return await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\openai_history_tracking_llm.py\", line 33, in __call__\n    output = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\caching_llm.py\", line 96, in __call__\n    result = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 177, in __call__\n    result, start = await execute_with_retry()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 159, in execute_with_retry\n    async for attempt in retryer:\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 166, in __anext__\n    do = await self.iter(retry_state=self._retry_state)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 153, in iter\n    result = await action(retry_state)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\_utils.py\", line 99, in inner\n    return call(*args, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\__init__.py\", line 418, in exc_check\n    raise retry_exc.reraise()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\__init__.py\", line 185, in reraise\n    raise self.last_attempt.result()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\concurrent\\futures\\_base.py\", line 451, in result\n    return self.__get_result()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\concurrent\\futures\\_base.py\", line 403, in __get_result\n    raise self._exception\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 165, in execute_with_retry\n    return await do_attempt(), start\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 151, in do_attempt\n    await sleep_for(sleep_time)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 147, in do_attempt\n    return await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 50, in __call__\n    return await self._invoke(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 54, in _invoke\n    output = await self._execute_llm(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\openai_chat_llm.py\", line 53, in _execute_llm\n    completion = await self.client.chat.completions.create(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\resources\\chat\\completions.py\", line 1633, in create\n    return await self._post(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\_base_client.py\", line 1838, in post\n    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\_base_client.py\", line 1532, in request\n    return await self._request(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\_base_client.py\", line 1633, in _request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 197223, Requested 7699. Please try again in 1.476s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}\n",
    "source": "Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 197223, Requested 7699. Please try again in 1.476s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}",
    "details": {
        "doc_index": 0,
        "text": "of their\nfirst class he took the roll call, and when he reached Harry's name he\ngave an excited squeak and toppled out of sight.\n\nProfessor McGonagall was again different. Harry had been quite right to\nthink she wasn't a teacher to cross. Strict and clever, she gave them a\ntalking-to the moment they sat down in her first class.\n\n\"Transfiguration is some of the most complex and dangerous magic you\nwill learn at Hogwarts,\" she said. \"Anyone messing around in my class\nwill leave and not come back. You have been warned.\"\n\nThen she changed her desk into a pig and back again. They were all very\nimpressed and couldn't wait to get started, but soon realized they\nweren't going to be changing the furniture into animals for a long time.\nAfter taking a lot of complicated notes, they were each given a match\nand started trying to turn it into a needle. By the end of the lesson,\nonly Hermione Granger had made any difference to her match; Professor\nMcGonagall showed the class how it had gone all silver and pointy and\ngave Hermione a rare smile.\n\nThe class everyone had really been looking forward to was Defense\nAgainst the Dark Arts, but Quirrell's lessons turned out to be a bit of\na joke. His classroom smelled strongly of garlic, which everyone said\nwas to ward off a vampire he'd met in Romania and was afraid would be\ncoming back to get him one of these days. His turban, he told them, had\nbeen given to him by an African prince as a thank-you for getting rid of\na troublesome zombie, but they weren't sure they believed this story.\nFor one thing, when Seamus Finnigan asked eagerly to hear how Quirrell\nhad fought off the zombie, Quirrell went pink and started talking about\nthe weather; for another, they had noticed that a funny smell hung\naround the turban, and the Weasley twins insisted that it was stuffed\nfull of garlic as well, so that Quirrell was protected wherever he went.\n\nHarry was very relieved to find out that he wasn't miles behind everyone\nelse. Lots of people had come from Muggle families and, like him, hadn't\nhad any idea that they were witches and wizards. There was so much to\nlearn that even people like Ron didn't have much of a head start.\n\nFriday was an important day for Harry and Ron. They finally managed to\nfind their way down to the Great Hall for breakfast without getting lost\nonce.\n\n\"What have we got today?\" Harry asked Ron as he poured sugar on his\nporridge.\n\n\"Double Potions with the Slytherins,\" said Ron. \"Snape's Head of\nSlytherin House. They say he always favors them -- we'll be able to see\nif it's true.\"\n\n\"Wish McGonagall favored us, \" said Harry. Professor McGonagall was head\nof Gryffindor House, but it hadn't stopped her from giving them a huge\npile of homework the day before.\n\nJust then, the mail arrived. Harry had gotten used to this by now, but\nit had given him a bit of a shock on the first morning, when about a\nhundred owls had suddenly streamed into the Great Hall during breakfast,\ncircling the tables until they saw their owners, and dropping letters\nand packages onto their laps.\n\nHedwig hadn't brought Harry anything so far. She sometimes flew in to\nnibble his ear and have a bit of toast before going off to sleep in the\nowlery with the other school owls. This morning, however, she fluttered\ndown between the marmalade and the sugar bowl and dropped a note onto\nHarry's plate. Harry tore it open at once. It said, in a very untidy\nscrawl:\n\n\nDear Harry,\n\nI know you get Friday afternoons off, so would you like to come and have\na cup of tea with me around three?\n\nI want to hear all about your first week. Send us an answer back with\nHedwig.\n\nHagrid\n\n\nHarry borrowed Ron's quill, scribbled Yes, please, see you later on the\nback of the note, and sent Hedwig off again.\n\nIt was lucky that Harry had tea with Hagrid to look forward to, because\nthe Potions lesson turned out to be the worst thing that had happened to\nhim so far.\n\nAt the start-of-term banquet, Harry had gotten the idea that Professor\nSnape disliked him. By the end of the first Potions lesson, he knew he'd\nbeen wrong. Snape didn't dislike Harry -- he hated him.\n\nPotions lessons took place down in one of the dungeons. It was colder\nhere than up in the main castle, and would have been quite creepy enough\nwithout the pickled animals floating in glass jars all around the walls.\n\nSnape, like Flitwick, started the class by taking the roll call, and\nlike Flitwick, he paused at Harry's name.\n\n\"Ah, Yes,\" he said softly, \"Harry Potter. Our new -- celebrity.\"\n\nDraco Malfoy and his friends Crabbe and Goyle sniggered behind their\nhands. Snape finished calling the names and looked up at the class. His\neyes were black like Hagrid's, but they had none of Hagrid's warmth.\nThey were cold and empty and made you think of dark tunnels.\n\n\"You are here to learn the subtle science and exact art of\npotionmaking,\" he began. He spoke in barely more than a whisper, but\nthey caught every word -- like Professor McGonagall, Snape had y caught\nevery word -- like Professor McGonagall, Snape had"
    }
}
{
    "type": "error",
    "data": "Entity Extraction Error",
    "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 122, in __call__\n    result = await self._process_document(text, prompt_variables)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 161, in _process_document\n    response = await self._llm(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\json_parsing_llm.py\", line 34, in __call__\n    result = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\openai_token_replacing_llm.py\", line 37, in __call__\n    return await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\openai_history_tracking_llm.py\", line 33, in __call__\n    output = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\caching_llm.py\", line 96, in __call__\n    result = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 177, in __call__\n    result, start = await execute_with_retry()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 159, in execute_with_retry\n    async for attempt in retryer:\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 166, in __anext__\n    do = await self.iter(retry_state=self._retry_state)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 153, in iter\n    result = await action(retry_state)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\_utils.py\", line 99, in inner\n    return call(*args, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\__init__.py\", line 418, in exc_check\n    raise retry_exc.reraise()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\__init__.py\", line 185, in reraise\n    raise self.last_attempt.result()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\concurrent\\futures\\_base.py\", line 451, in result\n    return self.__get_result()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\concurrent\\futures\\_base.py\", line 403, in __get_result\n    raise self._exception\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 165, in execute_with_retry\n    return await do_attempt(), start\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 151, in do_attempt\n    await sleep_for(sleep_time)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 147, in do_attempt\n    return await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 50, in __call__\n    return await self._invoke(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 54, in _invoke\n    output = await self._execute_llm(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\openai_chat_llm.py\", line 53, in _execute_llm\n    completion = await self.client.chat.completions.create(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\resources\\chat\\completions.py\", line 1633, in create\n    return await self._post(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\_base_client.py\", line 1838, in post\n    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\_base_client.py\", line 1532, in request\n    return await self._request(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\_base_client.py\", line 1633, in _request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 196895, Requested 7313. Please try again in 1.262s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}\n",
    "source": "Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 196895, Requested 7313. Please try again in 1.262s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}",
    "details": {
        "doc_index": 0,
        "text": "way along the rows of books. The lamp looked as if it was floating along\nin midair, and even though Harry could feel his arm supporting it, the\nsight gave him the creeps.\n\nThe Restricted Section was right at the back of the library. Step ping\ncarefully over the rope that separated these books from the rest of the\nlibrary, he held up his lamp to read the titles.\n\nThey didn't tell him much. Their peeling, faded gold letters spelled\nwords in languages Harry couldn't understand. Some had no title at all.\nOne book had a dark stain on it that looked horribly like blood. The\nhairs on the back of Harry's neck prickled. Maybe he was imagining it,\nmaybe not, but he thought a faint whispering was coming from the books,\nas though they knew someone was there who shouldn't be.\n\nHe had to start somewhere. Setting the lamp down carefully on the floor,\nhe looked along the bottom shelf for an interestinglooking book. A large\nblack and silver volume caught his eye. He pulled it out with\ndifficulty, because it was very heavy, and, balancing it on his knee,\nlet it fall open.\n\nA piercing, bloodcurdling shriek split the silence -- the book was\nscreaming! Harry snapped it shut, but the shriek went on and on, one\nhigh, unbroken, earsplitting note. He stumbled backward and knocked over\nhis lamp, which went out at once. Panicking, he heard footsteps coming\ndown the corridor outside -- stuffing the shrieking book back on the\nshelf, he ran for it. He passed Filch in the doorway; Filch's pale, wild\neyes looked straight through him, and Harry slipped under Filch's\noutstretched arm and streaked off up the corridor, the book's shrieks\nstill ringing in his ears.\n\nHe came to a sudden halt in front of a tall suit of armor. He had been\nso busy getting away from the library, he hadn't paid attention to where\nhe was going. Perhaps because it was dark, he didn't recognize where he\nwas at all. There was a suit of armor near the kitchens, he knew, but he\nmust be five floors above there.\n\n\"You asked me to come directly to you, Professor, if anyone was\nwandering around at night, and somebody's been in the library Restricted\nSection.\"\n\nHarry felt the blood drain out of his face. Wherever he was, Filch must\nknow a shortcut, because his soft, greasy voice was getting nearer, and\nto his horror, it was Snape who replied, \"The Restricted Section? Well,\nthey can't be far, we'll catch them.\"\n\nHarry stood rooted to the spot as Filch and Snape came around the corner\nahead. They couldn't see him, of course, but it was a narrow corridor\nand if they came much nearer they'd knock right into him -- the cloak\ndidn't stop him from being solid.\n\nHe backed away as quietly as he could. A door stood ajar to his left. It\nwas his only hope. He squeezed through it, holding his breath, trying\nnot to move it, and to his relief he managed to get inside the room\nwithout their noticing anything. They walked straight past, and Harry\nleaned against the wall, breathing deeply, listening to their footsteps\ndying away. That had been close, very close. It was a few seconds before\nhe noticed anything about the room he had hidden in.\n\nIt looked like an unused classroom. The dark shapes of desks and chairs\nwere piled against the walls, and there was an upturned wastepaper\nbasket -- but propped against the wall facing him was something that\ndidn't look as if it belonged there, something that looked as if someone\nhad just put it there to keep it out of the way.\n\nIt was a magnificent mirror, as high as the ceiling, with an ornate gold\nframe, standing on two clawed feet. There was an inscription carved\naround the top: Erised stra ehru oyt ube cafru oyt on wohsi. His panic\nfading now that there was no sound of Filch and Snape, Harry moved\nnearer to the mirror, wanting to look at himself but see no reflection\nagain. He stepped in front of it.\n\nHe had to clap his hands to his mouth to stop himself from screaming. He\nwhirled around. His heart was pounding far more furiously than when the\nbook had screamed -- for he had seen not only himself in the mirror, but\na whole crowd of people standing right behind him.\n\nBut the room was empty. Breathing very fast, he turned slowly back to\nthe mirror.\n\nThere he was, reflected in it, white and scared-looking, and there,\nreflected behind him, were at least ten others. Harry looked over his\nshoulder -- but still, no one was there. Or were they all invisible,\ntoo? Was he in fact in a room full of invisible people and this mirror's\ntrick was that it reflected them, invisible or not?\n\nHe looked in the mirror again. A woman standing right behind his\nreflection was smiling at him and waving. He reached out a hand and felt\nthe air behind him. If she was really there, he'd touch her, their\nreflections were so close together, but he felt only air -- she and the\nothers existed only in the mirror.\n\nShe was a very pretty woman. She had dark red hair and her eyes -- her\neyes are just like mine, Harry thought, edging a little closer to the\nglass. Bright green -- exactly the same shape, but then he noticed that\nshe was crying; smiling, but crying at the same"
    }
}
{
    "type": "error",
    "data": "Entity Extraction Error",
    "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 122, in __call__\n    result = await self._process_document(text, prompt_variables)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 161, in _process_document\n    response = await self._llm(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\json_parsing_llm.py\", line 34, in __call__\n    result = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\openai_token_replacing_llm.py\", line 37, in __call__\n    return await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\openai_history_tracking_llm.py\", line 33, in __call__\n    output = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\caching_llm.py\", line 96, in __call__\n    result = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 177, in __call__\n    result, start = await execute_with_retry()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 159, in execute_with_retry\n    async for attempt in retryer:\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 166, in __anext__\n    do = await self.iter(retry_state=self._retry_state)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 153, in iter\n    result = await action(retry_state)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\_utils.py\", line 99, in inner\n    return call(*args, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\__init__.py\", line 418, in exc_check\n    raise retry_exc.reraise()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\__init__.py\", line 185, in reraise\n    raise self.last_attempt.result()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\concurrent\\futures\\_base.py\", line 451, in result\n    return self.__get_result()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\concurrent\\futures\\_base.py\", line 403, in __get_result\n    raise self._exception\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 165, in execute_with_retry\n    return await do_attempt(), start\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 151, in do_attempt\n    await sleep_for(sleep_time)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 147, in do_attempt\n    return await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 50, in __call__\n    return await self._invoke(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 54, in _invoke\n    output = await self._execute_llm(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\openai_chat_llm.py\", line 53, in _execute_llm\n    completion = await self.client.chat.completions.create(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\resources\\chat\\completions.py\", line 1633, in create\n    return await self._post(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\_base_client.py\", line 1838, in post\n    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\_base_client.py\", line 1532, in request\n    return await self._request(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\_base_client.py\", line 1633, in _request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 195322, Requested 7504. Please try again in 847ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}\n",
    "source": "Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 195322, Requested 7504. Please try again in 847ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}",
    "details": {
        "doc_index": 0,
        "text": "a very good player yet and they kept\nshouting different bits of advice at him, which was confusing. \"Don't\nsend me there, can't you see his knight? Send him, we can afford to lose\nhim.\" On Christmas Eve, Harry went to bed looking forward to the next\nday for the food and the fun, but not expecting any presents at all.\nWhen he woke early in the morning, however, the first thing he saw was a\nsmall pile of packages at the foot of his bed.\n\n\"Merry Christmas,\" said Ron sleepily as Harry scrambled out of bed and\npulled on his bathrobe.\n\n\"You, too,\" said Harry. \"Will you look at this? I've got some presents!\"\n\n\"What did you expect, turnips?\" said Ron, turning to his own pile, which\nwas a lot bigger than Harry's.\n\nHarry picked up the top parcel. It was wrapped in thick brown paper and\nscrawled across it was To Harry, from Hagrid. Inside was a roughly cut\nwooden flute. Hagrid had obviously whittled it himself. Harry blew it --\nit sounded a bit like an owl.\n\nA second, very small parcel contained a note.\n\nWe received your message and enclose your Christmas present. From Uncle\nVernon and Aunt Petunia. Taped to the note was a fifty-pence piece.\n\n\"That's friendly,\" said Harry.\n\nRon was fascinated by the fifty pence.\n\n\"Weird!\" he said, 'NMat a shape! This is money?\"\n\n\"You can keep it,\" said Harry, laughing at how pleased Ron was. \"Hagrid\nand my aunt and uncle -- so who sent these?\"\n\n\"I think I know who that one's from,\" said Ron, turning a bit pink and\npointing to a very lumpy parcel. \"My mom. I told her you didn't expect\nany presents and -- oh, no,\" he groaned, \"she's made you a Weasley\nsweater.\"\n\nHarry had torn open the parcel to find a thick, hand-knitted sweater in\nemerald green and a large box of homemade fudge.\n\n\"Every year she makes us a sweater,\" said Ron, unwrapping his own, \"and\nmine's always maroon.\"\n\n\"That's really nice of her,\" said Harry, trying the fudge, which was\nvery tasty.\n\nHis next present also contained candy -- a large box of Chocolate Frogs\nfrom Hermione.\n\nThis only left one parcel. Harry picked it up and felt it. It was very\nlight. He unwrapped it.\n\nSomething fluid and silvery gray went slithering to the floor where it\nlay in gleaming folds. Ron gasped.\n\n\"I've heard of those,\" he said in a hushed voice, dropping the box of\nEvery Flavor Beans he'd gotten from Hermione. \"If that's what I think it\nis -- they're really rare, and really valuable.\"\n\n\"What is it?\"\n\nHarry picked the shining, silvery cloth off the floor. It was strange to\nthe touch, like water woven into material.\n\n\"It's an invisibility cloak,\" said Ron, a look of awe on his face. \"I'm\nsure it is -- try it on.\"\n\nHarry threw the cloak around his shoulders and Ron gave a yell.\n\n\"It is! Look down!\"\n\nHarry looked down at his feet, but they were gone. He dashed to the\nmirror. Sure enough, his reflection looked back at him, just his head\nsuspended in midair, his body completely invisible. He pulled the cloak\nover his head and his reflection vanished completely.\n\n\"There's a note!\" said Ron suddenly. \"A note fell out of it!\"\n\nHarry pulled off the cloak and seized the letter. Written in narrow,\nloopy writing he had never seen before were the following words: Your\nfather left this in my possession before he died. It is time it was\nreturned to you. Use it well.\n\nA Very Merry Christmas to you.\n\n\nThere was no signature. Harry stared at the note. Ron was admiring the\ncloak.\n\n\"I'd give anything for one of these,\" he said. \"Anything. What's the\nmatter?\"\n\n\"Nothing,\" said Harry. He felt very strange. Who had sent the cloak? Had\nit really once belonged to his father?\n\nBefore he could say or think anything else, the dormitory door was flung\nopen and Fred and George Weasley bounded in. Harry stuffed the cloak\nquickly out of sight. He didn't feel like sharing it with anyone else\nyet.\n\n\"Merry Christmas!\"\n\n\"Hey, look -- Harry's got a Weasley sweater, too!\"\n\nFred and George were wearing blue sweaters, one with a large yellow F on\nit, the other a G.\n\n\"Harry's is better than ours, though,\" said Fred, holding up Harry's\nsweater. \"She obviously makes more of an effort if you're not family.\"\n\n\"Why aren't you wearing yours, Ron?\" George demanded. \"Come on, get it\non, they're lovely and warm.\"\n\n\"I hate maroon,\" Ron moaned halfheartedly as he pulled it over his head.\n\n\"You haven't got a letter on yours,\" George observed. \"I suppose she\nthinks you don't forget your name. But we're not stupid -- we know we're\ncalled Gred and Forge.\"\n\n\"What's all th is noise.\n\nPercy Weasley stuck his head through the door, looking disapproving. He\nhad clearly gotten halfway through unwrapping his presents as he, too,\ncarried a lumpy sweater over his arm, which\n\nFred seized.\n\n\"P for prefect! Get it on, Percy, come on, we're all wearing ours, even\nHarry got one.\"\n\n\"I -- don't -- want said Percy thickly, as the twins"
    }
}
{
    "type": "error",
    "data": "Entity Extraction Error",
    "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 122, in __call__\n    result = await self._process_document(text, prompt_variables)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 161, in _process_document\n    response = await self._llm(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\json_parsing_llm.py\", line 34, in __call__\n    result = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\openai_token_replacing_llm.py\", line 37, in __call__\n    return await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\openai_history_tracking_llm.py\", line 33, in __call__\n    output = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\caching_llm.py\", line 96, in __call__\n    result = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 177, in __call__\n    result, start = await execute_with_retry()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 159, in execute_with_retry\n    async for attempt in retryer:\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 166, in __anext__\n    do = await self.iter(retry_state=self._retry_state)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 153, in iter\n    result = await action(retry_state)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\_utils.py\", line 99, in inner\n    return call(*args, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\__init__.py\", line 418, in exc_check\n    raise retry_exc.reraise()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\__init__.py\", line 185, in reraise\n    raise self.last_attempt.result()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\concurrent\\futures\\_base.py\", line 451, in result\n    return self.__get_result()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\concurrent\\futures\\_base.py\", line 403, in __get_result\n    raise self._exception\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 165, in execute_with_retry\n    return await do_attempt(), start\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 151, in do_attempt\n    await sleep_for(sleep_time)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 147, in do_attempt\n    return await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 50, in __call__\n    return await self._invoke(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 54, in _invoke\n    output = await self._execute_llm(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\openai_chat_llm.py\", line 53, in _execute_llm\n    completion = await self.client.chat.completions.create(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\resources\\chat\\completions.py\", line 1633, in create\n    return await self._post(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\_base_client.py\", line 1838, in post\n    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\_base_client.py\", line 1532, in request\n    return await self._request(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\_base_client.py\", line 1633, in _request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 193572, Requested 7938. Please try again in 453ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}\n",
    "source": "Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 193572, Requested 7938. Please try again in 453ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}",
    "details": {
        "doc_index": 0,
        "text": ".... D'you want the card, you\ncollect them, don't you?\"\n\nAs Neville walked away, Harry looked at the Famous Wizard card.\n\n\"Dumbledore again,\" he said, \"He was the first one I ever-\"\n\nHe gasped. He stared at the back of the card. Then he looked up at Ron\nand Hermione.\n\n\"I've found him!\" he whispered. \"I've found Flamel! I told you I'd read\nthe name somewhere before, I read it on the train coming here -- listen\nto this: 'Dumbledore is particularly famous for his defeat of the dark\nwizard Grindelwald in 1945, for the discovery of the twelve uses of\ndragon's blood, and his work on alchemy with his partner, Nicolas\nFlamel'!\"\n\nHermione jumped to her feet. She hadn't looked so excited since they'd\ngotten back the marks for their very first piece of homework.\n\n\"Stay there!\" she said, and she sprinted up the stairs to the girls'\ndormitories. Harry and Ron barely had time to exchange mystified looks\nbefore she was dashing back, an enormous old book in her arms.\n\n\"I never thought to look in here!\" she whispered excitedly. \"I got this\nout of the library weeks ago for a bit of light reading.\"\n\n\"Light?\" said Ron, but Hermione told him to be quiet until she'd looked\nsomething up, and started flicking frantically through the pages,\nmuttering to herself.\n\nAt last she found what she was looking for.\n\n\"I knew it! I knew it!\"\n\n\"Are we allowed to speak yet?\" said Ron grumpily. Hermione ignored him.\n\n\"Nicolas Flamel,\" she whispered dramatically, \"is the only known maker\nof the Sorcerer's Stone!\"\n\nThis didn't have quite the effect she'd expected.\n\n\"The what?\" said Harry and Ron.\n\n\"Oh, honestly, don't you two read? Look -- read that, there.\"\n\nShe pushed the book toward them, and Harry and Ron read: The ancient\nstudy of alchemy is concerned with making the Sorcerer's Stone, a\nlegendary substance with astonishing powers. The stone will transform\nany metal into pure gold. It also produces the Elixir of Life, which\nwill make the drinker immortal.\n\nThere have been many reports of the Sorcerer's Stone over the centuries,\nbut the only Stone currently in existence belongs to Mr. Nicolas Flamel,\nthe noted alchemist and opera lover. Mr. Flamel, who celebrated his six\nhundred and sixty-fifth birthday last year, enjoys a quiet life in Devon\nwith his wife, Perenelle (six hundred and fifty-eight).\n\n\"See?\" said Hermione, when Harry and Ron had finished. \"The dog must be\nguarding Flamel's Sorcerer's Stone! I bet he asked Dumbledore to keep it\nsafe for him, because they're friends and he knew someone was after it,\nthat's why he wanted the Stone moved out of Gringotts!\"\n\n\"A stone that makes gold and stops you from ever dying!\" said Harry. \"No\nwonder Snape's after it! Anyone would want it.\"\n\n\"And no wonder we couldn't find Flamel in that Study of Recent\nDevelopments in Wizardry,\" said Ron. \"He's not exactly recent if he's\nsix hundred and sixty-five, is he?\"\n\nThe next morning in Defense Against the Dark Arts, while copying down\ndifferent ways of treating werewolf bites, Harry and Ron were still\ndiscussing what they'd do with a Sorcerer's Stone if they had one. It\nwasn't until Ron said he'd buy his own Quidditch team that Harry\nremembered about Snape and the coming match.\n\n\"I'm going to play,\" he told Ron and Hermione. \"If I don't, all the\nSlytherins will think I'm just too scared to face Snape. I'll show\nthem... it'll really wipe the smiles off their faces if we win.\"\n\n\"Just as long as we're not wiping you off the field,\" said Hermione.\n\nAs the match drew nearer, however, Harry became more and more nervous,\nwhatever he told Ron and Hermione. The rest of the team wasn't too calm,\neither. The idea of overtaking Slytherin in the house championship was\nwonderful, no one had done it for seven years, but would they be allowed\nto, with such a biased referee?\n\nHarry didn't know whether he was imagining it or not, but he seemed to\nkeep running into Snape wherever he went. At times, he even wondered\nwhether Snape was following him, trying to catch him on his own. Potions\nlessons were turning into a sort of weekly torture, Snape was so\nhorrible to Harry. Could Snape possibly know they'd found out about the\nSorcerer's Stone? Harry didn't see how he could -- yet he sometimes had\nthe horrible feeling that Snape could read minds.\n\nHarry knew, when they wished him good luck outside the locker rooms the\nnext afternoon, that Ron and Hermione were wondering whether they'd ever\nsee him alive again. This wasn't what you'd call comforting. Harry\nhardly heard a word of Wood's pep talk as he pulled on his Quidditch\nrobes and picked up his Nimbus Two Thousand.\n\nRon and Hermione, meanwhile, had found a place in the stands next to\nNeville, who couldn't understand why they looked so grim and worried, or\nwhy they had both brought their wands to the match. Little did Harry\nknow that Ron and Hermione had been secretly practicing the Leg-Locker\nCurse. They'd gotten the idea from Malfoy using it on Neville, and were\nready to use it on Snape if he showed any sign of wanting to hurt Harry.\n\n\"Now, don"
    }
}
{
    "type": "error",
    "data": "Entity Extraction Error",
    "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 122, in __call__\n    result = await self._process_document(text, prompt_variables)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 161, in _process_document\n    response = await self._llm(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\json_parsing_llm.py\", line 34, in __call__\n    result = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\openai_token_replacing_llm.py\", line 37, in __call__\n    return await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\openai_history_tracking_llm.py\", line 33, in __call__\n    output = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\caching_llm.py\", line 96, in __call__\n    result = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 177, in __call__\n    result, start = await execute_with_retry()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 159, in execute_with_retry\n    async for attempt in retryer:\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 166, in __anext__\n    do = await self.iter(retry_state=self._retry_state)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 153, in iter\n    result = await action(retry_state)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\_utils.py\", line 99, in inner\n    return call(*args, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\__init__.py\", line 418, in exc_check\n    raise retry_exc.reraise()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\__init__.py\", line 185, in reraise\n    raise self.last_attempt.result()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\concurrent\\futures\\_base.py\", line 451, in result\n    return self.__get_result()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\concurrent\\futures\\_base.py\", line 403, in __get_result\n    raise self._exception\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 165, in execute_with_retry\n    return await do_attempt(), start\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 151, in do_attempt\n    await sleep_for(sleep_time)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 147, in do_attempt\n    return await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 50, in __call__\n    return await self._invoke(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 54, in _invoke\n    output = await self._execute_llm(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\openai_chat_llm.py\", line 53, in _execute_llm\n    completion = await self.client.chat.completions.create(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\resources\\chat\\completions.py\", line 1633, in create\n    return await self._post(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\_base_client.py\", line 1838, in post\n    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\_base_client.py\", line 1532, in request\n    return await self._request(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\_base_client.py\", line 1633, in _request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 193669, Requested 7689. Please try again in 407ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}\n",
    "source": "Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 193669, Requested 7689. Please try again in 407ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}",
    "details": {
        "doc_index": 0,
        "text": "later,\nthey were surprised to see that all the curtains were closed. Hagrid\ncalled \"Who is it?\" before he let them in, and then shut the door\nquickly behind them.\n\nIt was stifling hot inside. Even though it was such a warm day, there\nwas a blazing fire in the grate. Hagrid made them tea and offered them\nstoat sandwiches, which they refused.\n\n\"So -- yeh wanted to ask me somethin'?\"\n\n\"Yes,\" said Harry. There was no point beating around the bush. \"We were\nwondering if you could tell us what's guarding the Sorcerer's Stone\napart from Fluffy.\"\n\nHagrid frowned at him.\n\n\"0' course I cant, he said. \"Number one, I don' know meself. Number two,\nyeh know too much already, so I wouldn' tell yeh if I could. That\nStone's here fer a good reason. It Was almost stolen outta Gringotts - I\ns'ppose yeh've worked that out an' all? Beats me how yeh even know abou'\nFluffy.\"\n\n\"Oh, come on, Hagrid, you might not want to tell us, but you do know,\nyou know everything that goes on round here,\" said Hermione in a warm,\nflattering voice. Hagrid's beard twitched and they could tell he was\nsmiling. \"We only wondered who had done the guarding, really.\" Hermione\nwent on. \"We wondered who Dumbledore had trusted enough to help him,\napart from you.\"\n\nHagrid's chest swelled at these last words. Harry and Ron beamed at\nHermione.\n\n\"Well, I don' s'pose it could hurt ter tell yeh that... let's see... he\nborrowed Fluffy from me... then some o' the teachers did enchantments...\nProfessor Sprout -- Professor Flitwick -- Professor McGonagall --\" he\nticked them off on his fingers, \"Professor Quirrell -- an' Dumbledore\nhimself did somethin', o' course. Hang on, I've forgotten someone. Oh\nyeah, Professor Snape.\"\n\n\"Snape?\"\n\n\"Yeah -- yer not still on abou' that, are yeh? Look, Snape helped\nprotect the Stone, he's not about ter steal it.\"\n\nHarry knew Ron and Hermione were thinking the same as he was. If Snape\nhad been in on protecting the Stone, it must have been easy to find out\nhow the other teachers had guarded it. He probably knew everything --\nexcept, it seemed, Quirrell's spell and how to get past Fluffy.\n\n\"You're the only one who knows how to get past Fluffy. aren't you,\nHagrid?\" said Harry anxiously. \"And you wouldn't tell anyone, would you?\nNot even one of the teachers?\"\n\n\"Not a soul knows except me an' Dumbledore,\" said Hagrid proudly.\n\n\"Well, that's something,\" Harry muttered to the others. \"Hagrid, can we\nhave a window open? I'm boiling.\"\n\n\"Can't, Harry, sorry,\" said Hagrid. Harry noticed him glance at the\nfire. Harry looked at it, too.\n\n\"Hagrid -- what's that?\"\n\nBut he already knew what it was. In the very heart of the fire,\nunderneath the kettle, was a huge, black egg.\n\n\"Ah,\" said Hagrid, fiddling nervously with his beard, \"That's er...\"\n\n\"Where did you get it, Hagrid?\" said Ron, crouching over the fire to get\na closer look at the egg. \"It must've cost you a fortune.\"\n\n\"Won it,\" said Hagrid. \"Las' night. I was down in the village havin' a\nfew drinks an' got into a game o' cards with a stranger. Think he was\nquite glad ter get rid of it, ter be honest.\"\n\n\"But what are you going to do with it when it's hatched?\" said Hermione.\n\n\"Well, I've bin doin' some readin' , said Hagrid, pulling a large book\nfrom under his pillow. \"Got this outta the library -- Dragon Breeding\nfor Pleasure and Profit -- it's a bit outta date, o' course, but it's\nall in here. Keep the egg in the fire, 'cause their mothers breathe on I\nem, see, an' when it hatches, feed it on a bucket o' brandy mixed with\nchicken blood every half hour. An' see here -- how ter recognize\ndiff'rent eggs -- what I got there's a Norwegian Ridgeback. They're\nrare, them.\"\n\nHe looked very pleased with himself, but Hermione didn't.\n\n\"Hagrid, you live in a wooden house,\" she said.\n\nBut Hagrid wasn't listening. He was humming merrily as he stoked the\nfire.\n\nSo now they had something else to worry about: what might happen to\nHagrid if anyone found out he was hiding an illegal dragon in his hut.\n\"Wonder what it's like to have a peaceful life,\" Ron sighed, as evening\nafter evening they struggled through all the extra homework they were\ngetting. Hermione had now started making study schedules for Harry and\nRon, too. It was driving them nuts.\n\nThen, one breakfast time, Hedwig brought Harry another note from Hagrid.\nHe had written only two words: It's hatching.\n\nRon wanted to skip Herbology and go straight down to the hut. Hermione\nwouldn't hear of it.\n\n\"Hermione, how many times in our lives are we going to see a dragon\nhatching?\"\n\n\"We've got lessons, we'll get into trouble, and that's nothing to what\nHagrid's going to be in when"
    }
}
{
    "type": "error",
    "data": "Entity Extraction Error",
    "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 122, in __call__\n    result = await self._process_document(text, prompt_variables)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 161, in _process_document\n    response = await self._llm(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\json_parsing_llm.py\", line 34, in __call__\n    result = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\openai_token_replacing_llm.py\", line 37, in __call__\n    return await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\openai_history_tracking_llm.py\", line 33, in __call__\n    output = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\caching_llm.py\", line 96, in __call__\n    result = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 177, in __call__\n    result, start = await execute_with_retry()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 159, in execute_with_retry\n    async for attempt in retryer:\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 166, in __anext__\n    do = await self.iter(retry_state=self._retry_state)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 153, in iter\n    result = await action(retry_state)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\_utils.py\", line 99, in inner\n    return call(*args, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\__init__.py\", line 418, in exc_check\n    raise retry_exc.reraise()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\__init__.py\", line 185, in reraise\n    raise self.last_attempt.result()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\concurrent\\futures\\_base.py\", line 451, in result\n    return self.__get_result()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\concurrent\\futures\\_base.py\", line 403, in __get_result\n    raise self._exception\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 165, in execute_with_retry\n    return await do_attempt(), start\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 151, in do_attempt\n    await sleep_for(sleep_time)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 147, in do_attempt\n    return await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 50, in __call__\n    return await self._invoke(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 54, in _invoke\n    output = await self._execute_llm(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\openai_chat_llm.py\", line 53, in _execute_llm\n    completion = await self.client.chat.completions.create(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\resources\\chat\\completions.py\", line 1633, in create\n    return await self._post(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\_base_client.py\", line 1838, in post\n    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\_base_client.py\", line 1532, in request\n    return await self._request(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\_base_client.py\", line 1633, in _request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 199585, Requested 7790. Please try again in 2.212s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}\n",
    "source": "Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 199585, Requested 7790. Please try again in 2.212s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}",
    "details": {
        "doc_index": 0,
        "text": "hall and along the dark corridors. UP another\nstaircase, then another -- even one of Harry's shortcuts didn't make the\nwork much easier.\n\n\"Nearly there!\" Harry panted as they reached the corridor beneath the\ntallest tower.\n\nThen a sudden movement ahead of them made them almost drop the crate.\nForgetting that they were already invisible, they shrank into the\nshadows, staring at the dark outlines of two people grappling with each\nother ten feet away. A lamp flared.\n\nProfessor McGonagall, in a tartan bathrobe and a hair net, had Malfoy by\nthe ear.\n\n\"Detention!\" she shouted. \"And twenty points from Slytherin! Wandering\naround in the middle of the night, how dare you --\"\n\n\"You don't understand, Professor. Harry Potter's coming -- he's got a\ndragon!\"\n\n\"What utter rubbish! How dare you tell such lies! Come on -- I shall see\nProfessor Snape about you, Malfoy!\"\n\nThe steep spiral staircase up to the top of the tower seemed the easiest\nthing in the world after that. Not until they'd stepped out into the\ncold night air did they throw off the cloak, glad to be able to breathe\nproperly again. Hermione did a sort of jig.\n\n\"Malfoy's got detention! I could sing!\"\n\n\"Don't,\" Harry advised her.\n\nChuckling about Malfoy, they waited, Norbert thrashing about in his\ncrate. About ten minutes later, four broomsticks came swooping down out\nof the darkness.\n\nCharlie's friends were a cheery lot. They showed Harry and Hermione the\nharness they'd rigged up, so they could suspend Norbert between them.\nThey all helped buckle Norbert safely into it and then Harry and\nHermione shook hands with the others and thanked them very much.\n\nAt last, Norbert was going... going... gone.\n\nThey slipped back down the spiral staircase, their hearts as light as\ntheir hands, now that Norbert was off them. No more dragon -- Malfoy in\ndetention -- what could spoil their happiness?\n\nThe answer to that was waiting at the foot of the stairs. As they\nstepped into the corridor, Filch's face loomed suddenly out of the\ndarkness.\n\n\"Well, well, well,\" he whispered, \"we are in trouble.\"\n\nThey'd left the invisibility cloak on top of the tower.\n\n\nCHAPTER FIFTEEN\n\nTHE FORIBIDDEN FOREST\n\nThings couldn't have been worse.\n\nFilch took them down to Professor McGonagall's study on the first floor,\nwhere they sat and waited without saying a word to each other. Hermione\nwas trembling. Excuses, alibis, and wild cover- up stories chased each\nother around Harry's brain, each more feeble than the last. He couldn't\nsee how they were going to get out of trouble this time. They were\ncornered. How could they have been so stupid as to forget the cloak?\nThere was no reason on earth that Professor McGonagall would accept for\ntheir being out of bed and creeping around the school in the dead of\nnight, let alone being up the tallest astronomy tower, which was\nout-of-bounds except for classes. Add Norbert and the invisibility\ncloak, and they might as well be packing their bags already.\n\nHad Harry thought that things couldn't have been worse? He was wrong.\nWhen Professor McGonagall appeared, she was leading Neville.\n\n\"Harry!\" Neville burst Out, the moment he saw the other two. \"I was\ntrying to find you to warn you, I heard Malfoy saying he was going to\ncatch you, he said you had a drag --\"\n\nHarry shook his head violently to shut Neville up, but Professor\nMcGonagall had seen. She looked more likely to breathe fire than Norbert\nas she towered over the three of them.\n\n\"I would never have believed it of any of you. Mr. Filch says you were\nup in the astronomy tower. It's one o'clock in the morning. Explain\nyourselves.\"\n\nIt was the first time Hermione had ever failed to answer a teacher's\nquestion. She was staring at her slippers, as still as a statue.\n\n\"I think I've got a good idea of what's been going on,\" said Professor\nMcGonagall. \"It doesn't take a genius to work it out. You fed Draco\nMalfoy some cock-and-bull story about a dragon, trying to get him out of\nbed and into trouble. I've already caught him. I suppose you think it's\nfunny that Longbottom here heard the story and believed it, too?\"\n\nHarry caught Neville's eye and tried to tell him without words that this\nwasn't true, because Neville was looking stunned and hurt. Poor,\nblundering Neville -- Harry knew what it must have cost him to try and\nfind them in the dark, to warn them.\n\n\"I'm disgusted,\" said Professor McGonagall. \"Four students out of bed in\none night! I've never heard of such a thing before! You, Miss Granger, I\nthought you had more sense. As for you, Mr. Potter, I thought Gryffindor\nmeant more to you than this. All three of you will receive detentions --\nyes, you too, Mr. Longbottom, nothing gives you the right to walk around\nschool at night, especially these days, it's very dangerous -- and fifty\npoints will be taken from Gryffindor.\"\n\n\"Fifty?\" Harry gasped -- they would lose the lead, the lead he'd won in\nthe last Quidditch match.\n\n\"Fifty points each,\" said Professor McGonagall, breathing heavily\nthrough her"
    }
}
{
    "type": "error",
    "data": "Entity Extraction Error",
    "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 122, in __call__\n    result = await self._process_document(text, prompt_variables)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 161, in _process_document\n    response = await self._llm(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\json_parsing_llm.py\", line 34, in __call__\n    result = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\openai_token_replacing_llm.py\", line 37, in __call__\n    return await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\openai_history_tracking_llm.py\", line 33, in __call__\n    output = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\caching_llm.py\", line 96, in __call__\n    result = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 177, in __call__\n    result, start = await execute_with_retry()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 159, in execute_with_retry\n    async for attempt in retryer:\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 166, in __anext__\n    do = await self.iter(retry_state=self._retry_state)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 153, in iter\n    result = await action(retry_state)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\_utils.py\", line 99, in inner\n    return call(*args, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\__init__.py\", line 418, in exc_check\n    raise retry_exc.reraise()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\__init__.py\", line 185, in reraise\n    raise self.last_attempt.result()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\concurrent\\futures\\_base.py\", line 451, in result\n    return self.__get_result()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\concurrent\\futures\\_base.py\", line 403, in __get_result\n    raise self._exception\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 165, in execute_with_retry\n    return await do_attempt(), start\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 151, in do_attempt\n    await sleep_for(sleep_time)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 147, in do_attempt\n    return await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 50, in __call__\n    return await self._invoke(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 54, in _invoke\n    output = await self._execute_llm(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\openai_chat_llm.py\", line 53, in _execute_llm\n    completion = await self.client.chat.completions.create(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\resources\\chat\\completions.py\", line 1633, in create\n    return await self._post(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\_base_client.py\", line 1838, in post\n    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\_base_client.py\", line 1532, in request\n    return await self._request(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\_base_client.py\", line 1633, in _request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 195537, Requested 7549. Please try again in 925ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}\n",
    "source": "Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 195537, Requested 7549. Please try again in 925ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}",
    "details": {
        "doc_index": 0,
        "text": "of candles.\n\n\"How many days you got left until yer holidays?\" Hagrid asked.\n\n\"Just one,\" said Hermione. \"And that reminds me -Harry, Ron, we've got\nhalf an hour before lunch, we should be in the library.\"\n\n\"Oh yeah, you're right,\" said Ron, tearing his eyes away from Professor\nFlitwick, who had golden bubbles blossoming out of his wand and was\ntrailing them over the branches of the new tree.\n\n\"The library?\" said Hagrid, following them out of the hall. \"Just before\nthe holidays? Bit keen, aren't yeh?\"\n\n\"Oh, we're not working,\" Harry told him brightly. \"Ever since you\nmentioned Nicolas Flamel we've been trying to find out who he is.\"\n\n\"You what?\" Hagrid looked shocked. \"Listen here -- I've told yeh -- drop\nit. It's nothin' to you what that dog's guardin'.\"\n\n\"We just want to know who Nicolas Flamel is, that's all,\" said Hermione.\n\n\"Unless you'd like to tell us and save us the trouble?\" Harry added. \"We\nmust've been through hundreds of books already and we can't find him\nanywhere -- just give us a hint -- I know I've read his name somewhere.\"\n\n\"I'm sayin' nothin, said Hagrid flatly.\n\n\"Just have to find out for ourselves, then,\" said Ron, and they left\nHagrid looking disgruntled and hurried off to the library.\n\nThey had indeed been searching books for Flamel's name ever since Hagrid\nhad let it slip, because how else were they going to find out what Snape\nwas trying to steal? The trouble was, it was very hard to know where to\nbegin, not knowing what Flamel might have done to get himself into a\nbook. He wasn't in Great Wizards of the Twentieth Century, or Notable\nMagical Names of Our Time; he was missing, too, from Important Modern\nMagical Discoveries, and A Study of Recent Developments in Wizardry. And\nthen, of course, there was the sheer size of the library; tens of\nthousands of books; thousands of shelves; hundreds of narrow rows.\n\nHermione took out a list of subjects and titles she had decided to\nsearch while Ron strode off down a row of books and started pulling them\noff the shelves at random. Harry wandered over to the Restricted\nSection. He had been wondering for a while if Flamel wasn't somewhere in\nthere. Unfortunately, you needed a specially signed note from one of the\nteachers to look in any of the restricted books, and he knew he'd never\nget one. These were the books containing powerful Dark Magic never\ntaught at Hogwarts, and only read by older students studying advanced\nDefense Against the Dark Arts.\n\n\"What are you looking for, boy?\"\n\n\"Nothing,\" said Harry.\n\nMadam Pince the librarian brandished a feather duster at him.\n\n\"You'd better get out, then. Go on -- out!\"\n\nWishing he'd been a bit quicker at thinking up some story, Harry left\nthe library. He, Ron, and Hermione had already agreed they'd better not\nask Madam Pince where they could find Flamel. They were sure she'd be\nable to tell them, but they couldn't risk Snape hearing what they were\nup to.\n\nHarry waited outside in the corridor to see if the other two had found\nanything, but he wasn't very hopeful. They had been looking for two\nweeks, after A, but as they only had odd moments between lessons it\nwasn't surprising they'd found nothing. What they really needed was a\nnice long search without Madam Pince breathing down their necks.\n\nFive minutes later, Ron and Hermione joined him, shaking their heads.\nThey went off to lunch.\n\n\"You will keep looking while I'm away, won't you?\" said Hermione. \"And\nsend me an owl if you find anything.\"\n\n\"And you could ask your parents if they know who Flamel is,\" said Ron.\n\"It'd be safe to ask them.\"\n\n\"Very safe, as they're both dentists,\" said Hermione.\n\nOnce the holidays had started, Ron and Harry were having too good a time\nto think much about Flamel. They had the dormitory to themselves and the\ncommon room was far emptier than usual, so they were able to get the\ngood armchairs by the fire. They sat by the hour eating anything they\ncould spear on a toasting fork -- bread, English muffins, marshmallows\n-- and plotting ways of getting Malfoy expelled, which were fun to talk\nabout even if they wouldn't work.\n\nRon also started teaching Harry wizard chess. This was exactly like\nMuggle chess except that the figures were alive, which made it a lot\nlike directing troops in battle. Ron's set was very old and battered.\nLike everything else he owned, it had once belonged to someone else in\nhis family -- in this case, his grandfather. However, old chessmen\nweren't a drawback at all. Ron knew them so well he never had trouble\ngetting them to do what he wanted.\n\nHarry played with chessmen Seamus Finnigan had lent him, and they didn't\ntrust him at all. He wasn't a very good player yet and they kept\nshouting different bits of advice at him, which was confusing. \"Don't\nsend me there, can't you see his knight? Send him, we can afford to lose\nhim.\" On Christmas Eve, Harry went to bed looking forward to the next\nday for the food and the fun, but not expecting any presents at all.\nWhen he woke early in the morning, however, the first thing he saw was a\nsmall pile of packages"
    }
}
{
    "type": "error",
    "data": "Entity Extraction Error",
    "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 122, in __call__\n    result = await self._process_document(text, prompt_variables)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 161, in _process_document\n    response = await self._llm(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\json_parsing_llm.py\", line 34, in __call__\n    result = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\openai_token_replacing_llm.py\", line 37, in __call__\n    return await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\openai_history_tracking_llm.py\", line 33, in __call__\n    output = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\caching_llm.py\", line 96, in __call__\n    result = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 177, in __call__\n    result, start = await execute_with_retry()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 159, in execute_with_retry\n    async for attempt in retryer:\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 166, in __anext__\n    do = await self.iter(retry_state=self._retry_state)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 153, in iter\n    result = await action(retry_state)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\_utils.py\", line 99, in inner\n    return call(*args, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\__init__.py\", line 418, in exc_check\n    raise retry_exc.reraise()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\__init__.py\", line 185, in reraise\n    raise self.last_attempt.result()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\concurrent\\futures\\_base.py\", line 451, in result\n    return self.__get_result()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\concurrent\\futures\\_base.py\", line 403, in __get_result\n    raise self._exception\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 165, in execute_with_retry\n    return await do_attempt(), start\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 151, in do_attempt\n    await sleep_for(sleep_time)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 147, in do_attempt\n    return await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 50, in __call__\n    return await self._invoke(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 54, in _invoke\n    output = await self._execute_llm(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\openai_chat_llm.py\", line 53, in _execute_llm\n    completion = await self.client.chat.completions.create(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\resources\\chat\\completions.py\", line 1633, in create\n    return await self._post(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\_base_client.py\", line 1838, in post\n    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\_base_client.py\", line 1532, in request\n    return await self._request(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\_base_client.py\", line 1633, in _request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 193132, Requested 7390. Please try again in 156ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}\n",
    "source": "Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 193132, Requested 7390. Please try again in 156ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}",
    "details": {
        "doc_index": 0,
        "text": "unny rabbit. When it bit me he told me off for frightening it. And when\nI left, he was singing it a lullaby.\"\n\nThere was a tap on the dark window.\n\n\"It's Hedwig!\" said Harry, hurrying to let her in. \"She'll have\nCharlie's answer!\"\n\nThe three of them put their heads together to read the note.\n\nDear Ron,\n\nHow are you? Thanks for the letter -- I'd be glad to take the Norwegian\nRidgeback, but it won't be easy getting him here. I think the best thing\nwill be to send him over with some friends of mine who are coming to\nvisit me next week. Trouble is, they mustn't be seen carrying an illegal\ndragon.\n\nCould you get the Ridgeback up the tallest tower at midnight on\nSaturday? They can meet you there and take him away while it's still\ndark.\n\nSend me an answer as soon as possible.\n\nLove,\n\nCharlie\n\nThey looked at one another.\n\n\"We've got the invisibility cloak,\" said Harry. \"It shouldn't be too\ndifficult -- I think the cloaks big enough to cover two of us and\nNorbert.\"\n\nIt was a mark of how bad the last week had been that the other two\nagreed with him. Anything to get rid of Norbert -- and Malfoy.\n\nThere was a hitch. By the next morning, Ron's bitten hand had swollen to\ntwice its usual size. He didn't know whether it was safe to go to Madam\nPomfrey -- would she recognize a dragon bite? By the afternoon, though,\nhe had no choice. The cut had turned a nasty shade of green. It looked\nas if Norbert's fangs were poisonous.\n\nHarry and Hermione rushed up to the hospital wing at the end of the day\nto find Ron in a terrible state in bed.\n\n\"It's not just my hand,\" he whispered, \"although that feels like it's\nabout to fall off. Malfoy told Madam Pomfrey he wanted to borrow one of\nmy books so he could come and have a good laugh at me. He kept\nthreatening to tell her what really bit me -- I've told her it was a\ndog, but I don't think she believes me -I shouldn't have hit him at the\nQuidditch match, that's why he's doing this.\"\n\nHarry and Hermione tried to calm Ron down.\n\n\"It'll all be over at midnight on Saturday,\" said Hermione, but this\ndidn't soothe Ron at all. On the contrary, he sat bolt upright and broke\ninto a sweat.\n\n\"Midnight on Saturday!\" he said in a hoarse voice. \"Oh no oh no -- I've\njust remembered -- Charlie's letter was in that book Malfoy took, he's\ngoing to know we're getting rid of Norbert.\"\n\nHarry and Hermione didn't get a chance to answer. Madam Pomfrey came\nover at that moment and made them leave, saying Ron needed sleep.\n\n\"It's too late to change the plan now,\" Harry told Hermione. \"We haven't\ngot time to send Charlie another owl, and this could be our only chance\nto get rid of Norbert. We'll have to risk it. And we have got the\ninvisibility cloak, Malfoy doesn't know about that.\"\n\nThey found Fang, the boarhound, sitting outside with a bandaged tail\nwhen they went to tell Hagrid, who opened a window to talk to them.\n\n\"I won't let you in,\" he puffed. \"Norbert's at a tricky stage -- nothin'\nI can't handle.\"\n\nWhen they told him about Charlie's letter, his eyes filled with tears,\nalthough that might have been because Norbert had just bitten him on the\nleg.\n\n\"Aargh! It's all right, he only got my boot -- jus' playin' -- he's only\na baby, after all.\"\n\nThe baby banged its tail on the wall, making the windows rattle. Harry\nand Hermione walked back to the castle feeling Saturday couldn't come\nquickly enough.\n\nThey would have felt sorry for Hagrid when the time came for him to say\ngood-bye to Norbert if they hadn't been so worried about what they had\nto do. It was a very dark, cloudy night, and they were a bit late\narriving at Hagrid's hut because they'd had to wait for Peeves to get\nout of their way in the entrance hall, where he'd been playing tennis\nagainst the wall. Hagrid had Norbert packed and ready in a large crate.\n\n\"He's got lots o' rats an' some brandy fer the journey,\" said Hagrid in\na muffled voice. \"An' I've packed his teddy bear in case he gets\nlonely.\"\n\nFrom inside the crate came ripping noises that sounded to Harry as\nthough the teddy was having his head torn off.\n\n\"Bye-bye, Norbert!\" Hagrid sobbed, as Harry and Hermione covered the\ncrate with the invisibility cloak and stepped underneath it themselves.\n\"Mommy will never forget you!\"\n\nHow they managed to get the crate back up to the castle, they never\nknew. Midnight ticked nearer as they heaved Norbert up the marble\nstaircase in the entrance hall and along the dark corridors. UP another\nstaircase, then another -- even one of Harry's shortcuts didn't make the\nwork much easier.\n\n\"Nearly there!\" Harry panted as they reached the corridor beneath the\ntallest tower.\n\nThen a sudden movement ahead of them made them almost drop the crate.\nForgetting that they were already invisible, they shrank into the\nshadows, staring at the dark outlines of two people grappling with each\nother ten feet away. A"
    }
}
{
    "type": "error",
    "data": "Entity Extraction Error",
    "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 122, in __call__\n    result = await self._process_document(text, prompt_variables)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 161, in _process_document\n    response = await self._llm(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\json_parsing_llm.py\", line 34, in __call__\n    result = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\openai_token_replacing_llm.py\", line 37, in __call__\n    return await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\openai_history_tracking_llm.py\", line 33, in __call__\n    output = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\caching_llm.py\", line 96, in __call__\n    result = await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 177, in __call__\n    result, start = await execute_with_retry()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 159, in execute_with_retry\n    async for attempt in retryer:\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 166, in __anext__\n    do = await self.iter(retry_state=self._retry_state)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 153, in iter\n    result = await action(retry_state)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\_utils.py\", line 99, in inner\n    return call(*args, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\__init__.py\", line 418, in exc_check\n    raise retry_exc.reraise()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\tenacity\\__init__.py\", line 185, in reraise\n    raise self.last_attempt.result()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\concurrent\\futures\\_base.py\", line 451, in result\n    return self.__get_result()\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\concurrent\\futures\\_base.py\", line 403, in __get_result\n    raise self._exception\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 165, in execute_with_retry\n    return await do_attempt(), start\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 151, in do_attempt\n    await sleep_for(sleep_time)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 147, in do_attempt\n    return await self._delegate(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 50, in __call__\n    return await self._invoke(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 54, in _invoke\n    output = await self._execute_llm(input, **kwargs)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\graphrag\\llm\\openai\\openai_chat_llm.py\", line 53, in _execute_llm\n    completion = await self.client.chat.completions.create(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\resources\\chat\\completions.py\", line 1633, in create\n    return await self._post(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\_base_client.py\", line 1838, in post\n    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\_base_client.py\", line 1532, in request\n    return await self._request(\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\lib\\site-packages\\openai\\_base_client.py\", line 1633, in _request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 196847, Requested 7701. Please try again in 1.364s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}\n",
    "source": "Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 196847, Requested 7701. Please try again in 1.364s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}",
    "details": {
        "doc_index": 0,
        "text": "nearly raised the bewitched ceiling; the stars\noverhead seemed to quiver. Percy could be heard telling the other\nprefects, \"My brother, you know! My youngest brother! Got past\nMcGonagall's giant chess set!\"\n\nAt last there was silence again.\n\n\"Second -- to Miss Hermione Granger... for the use of cool logic in the\nface of fire, I award Gryffindor house fifty points.\"\n\nHermione buried her face in her arms; Harry strongly suspected she had\nburst into tears. Gryffindors up and down the table were beside\nthemselves -- they were a hundred points up. \"Third -- to Mr. Harry\nPotter...\" said Dumbledore. The room went deadly quiet for pure nerve\nand outstanding courage, I award Gryffindor house sixty points.\"\n\nThe din was deafening. Those who could add up while yelling themselves\nhoarse knew that Gryffindor now had four hundred and seventy-two points\n-- exactly the same as Slytherin. They had tied for the house cup -- if\nonly Dumbledore had given Harry just one more point.\n\nDumbledore raised his hand. The room gradually fell silent.\n\n\"There are all kinds of courage,\" said Dumbledore, smiling. \"It takes a\ngreat deal of bravery to stand up to our enemies, but just as much to\nstand up to our friends. I therefore award ten points to Mr. Neville\nLongbottom.\"\n\nSomeone standing outside the Great Hall might well have thought some\nsort of explosion had taken place, so loud was the noise that erupted\nfrom the Gryffindor table. Harry, Ron, and Hermione stood up to yell and\ncheer as Neville, white with shock, disappeared under a pile of people\nhugging him. He had never won so much as a point for Gryffindor before.\nHarry, still cheering, nudged Ron in the ribs and pointed at Malfoy, who\ncouldn't have looked more stunned and horrified if he'd just had the\nBody-Bind Curse put on him.\n\n\"Which means, Dumbledore called over the storm of applause, for even\nRavenclaw and Hufflepuff were celebrating the downfall of Slytherin, \"we\nneed a little change of decoration.\"\n\nHe clapped his hands. In an instant, the green hangings became scarlet\nand the silver became gold; the huge Slytherin serpent vanished and a\ntowering Gryffindor lion took its place. Snape was shaking Professor\nMcGonagall's hand, with a horrible, forced smile. He caught Harry's eye\nand Harry knew at once that Snape's feelings toward him hadn't changed\none jot. This didn't worry Harry. It seemed as though life would be back\nto normal next year, or as normal as it ever was at Hogwarts.\n\nIt was the best evening of Harry's life, better than winning at\nQuidditch, or Christmas, or knocking out mountain trolls... he would\nnever, ever forget tonight.\n\nHarry had almost forgotten that the exam results were still to come, but\ncome they did. To their great surprise, both he and Ron passed with good\nmarks; Hermione, of course, had the best grades of the first years. Even\nNeville scraped through, his good Herbology mark making up for his\nabysmal Potions one. They had hoped that Goyle, who was almost as stupid\nas he was mean, might be thrown out, but he had passed, too. It was a\nshame, but as Ron said, you couldn't have everything in life.\n\nAnd suddenly, their wardrobes were empty, their trunks were packed,\nNeville's toad was found lurking in a corner of the toilets; notes were\nhanded out to all students, warning them not to use magic over the\nholidays (\"I always hope they'll forget to give us these,\" said Fred\nWeasley sadly); Hagrid was there to take them down to the fleet of boats\nthat sailed across the lake; they were boarding the Hogwarts Express;\ntalking and laughing as the countryside became greener and tidier;\neating Bettie Bott's Every Flavor Beans as they sped past Muggle towns;\npulling off their wizard robes and putting on jackets and coats; pulling\ninto platform nine and three-quarters at King's Cross Station.\n\nIt took quite a while for them all to get off the platform. A wizened\nold guard was up by the ticket barrier, letting them go through the gate\nin twos and threes so they didn't attract attention by all bursting out\nof a solid wall at once and alarming the Muggles.\n\n\"You must come and stay this summer,\" said Ron, \"both of you -- I'll\nsend you an owl.\"\n\n\"Thanks,\" said Harry, \"I'll need something to look forward to.\" People\njostled them as they moved forward toward the gateway back to the Muggle\nworld. Some of them called:\n\n\"Bye, Harry!\"\n\n\"See you, Potter!\"\n\n\"Still famous,\" said Ron, grinning at him.\n\n\"Not where I'm going, I promise you,\" said Harry.\n\nHe, Ron, and Hermione passed through the gateway together. \"There he is,\nMom, there he is, look!\"\n\nIt was Ginny Weasley, Ron's younger sister, but she wasn't pointing at\nRon.\n\n\"Harry Potter!\" she squealed. \"Look, Mom! I can see\n\n\"Be quiet, Ginny, and it's rude to point.\"\n\nMrs. Weasley smiled down at them.\n\n\"Busy year?\" she said.\n\n\"Very,\" said Harry. \"Thanks for the fudge and the sweater, Mrs.\nWeasley.\"\n\n\"Oh, it was nothing, dear.\"\n\n\"Ready, are you?\"\n\nIt was Uncle Vernon,"
    }
}
