{
    "type": "error",
    "data": "Error Invoking LLM",
    "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 72, in map_httpcore_exceptions\n    yield\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 377, in handle_async_request\n    resp = await self._pool.handle_async_request(req)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 256, in handle_async_request\n    raise exc from None\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 236, in handle_async_request\n    response = await connection.handle_async_request(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\httpcore\\_async\\connection.py\", line 103, in handle_async_request\n    return await self._connection.handle_async_request(request)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\httpcore\\_async\\http11.py\", line 136, in handle_async_request\n    raise exc\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\httpcore\\_async\\http11.py\", line 106, in handle_async_request\n    ) = await self._receive_response_headers(**kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\httpcore\\_async\\http11.py\", line 177, in _receive_response_headers\n    event = await self._receive_event(timeout=timeout)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\httpcore\\_async\\http11.py\", line 231, in _receive_event\n    raise RemoteProtocolError(msg)\nhttpcore.RemoteProtocolError: Server disconnected without sending a response.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1572, in _request\n    response = await self._client.send(\n               ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\httpx\\_client.py\", line 1674, in send\n    response = await self._send_handling_auth(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\httpx\\_client.py\", line 1702, in _send_handling_auth\n    response = await self._send_handling_redirects(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\httpx\\_client.py\", line 1739, in _send_handling_redirects\n    response = await self._send_single_request(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\httpx\\_client.py\", line 1776, in _send_single_request\n    response = await transport.handle_async_request(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 376, in handle_async_request\n    with map_httpcore_exceptions():\n         ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\contextlib.py\", line 158, in __exit__\n    self.gen.throw(value)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 89, in map_httpcore_exceptions\n    raise mapped_exc(message) from exc\nhttpx.RemoteProtocolError: Server disconnected without sending a response.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 54, in _invoke\n    output = await self._execute_llm(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_chat_llm.py\", line 53, in _execute_llm\n    completion = await self.client.chat.completions.create(\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\resources\\chat\\completions.py\", line 1661, in create\n    return await self._post(\n           ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1839, in post\n    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1533, in request\n    return await self._request(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1606, in _request\n    raise APIConnectionError(request=request) from err\nopenai.APIConnectionError: Connection error.\n",
    "source": "Connection error.",
    "details": {
        "input": "MANY entities and relationships were missed in the last extraction. Remember to ONLY emit entities that match any of the previously extracted types. Add them below using the same format:\n"
    }
}
{
    "type": "error",
    "data": "Entity Extraction Error",
    "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 122, in __call__\n    result = await self._process_document(text, prompt_variables)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 161, in _process_document\n    response = await self._llm(\n               ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\json_parsing_llm.py\", line 34, in __call__\n    result = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_token_replacing_llm.py\", line 37, in __call__\n    return await self._delegate(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_history_tracking_llm.py\", line 33, in __call__\n    output = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\caching_llm.py\", line 96, in __call__\n    result = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 177, in __call__\n    result, start = await execute_with_retry()\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 159, in execute_with_retry\n    async for attempt in retryer:\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 166, in __anext__\n    do = await self.iter(retry_state=self._retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 153, in iter\n    result = await action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\_utils.py\", line 99, in inner\n    return call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\__init__.py\", line 418, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\__init__.py\", line 185, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\concurrent\\futures\\_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\concurrent\\futures\\_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 165, in execute_with_retry\n    return await do_attempt(), start\n           ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 151, in do_attempt\n    await sleep_for(sleep_time)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 147, in do_attempt\n    return await self._delegate(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 50, in __call__\n    return await self._invoke(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 54, in _invoke\n    output = await self._execute_llm(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_chat_llm.py\", line 53, in _execute_llm\n    completion = await self.client.chat.completions.create(\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\resources\\chat\\completions.py\", line 1661, in create\n    return await self._post(\n           ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1839, in post\n    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1533, in request\n    return await self._request(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1634, in _request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 195501, Requested 7132. Please try again in 789ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}\n",
    "source": "Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 195501, Requested 7132. Please try again in 789ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}",
    "details": {
        "doc_index": 0,
        "text": "in the doorway. His face was almost\ncompletely hidden by a long, shaggy mane of hair and a wild, tangled\nbeard, but you could make out his eyes, glinting like black beetles\nunder all the hair.\n\nThe giant squeezed his way into the hut, stooping so that his head just\nbrushed the ceiling. He bent down, picked up the door, and fitted it\neasily back into its frame. The noise of the storm outside dropped a\nlittle. He turned to look at them all.\n\n\"Couldn't make us a cup o' tea, could yeh? It's not been an easy\njourney...\"\n\nHe strode over to the sofa where Dudley sat frozen with fear.\n\n\"Budge up, yeh great lump,\" said the stranger.\n\nDudley squeaked and ran to hide behind his mother, who was crouching,\nterrified, behind Uncle Vernon.\n\n\"An' here's Harry!\" said the giant.\n\nHarry looked up into the fierce, wild, shadowy face and saw that the\nbeetle eyes were crinkled in a smile.\n\n\"Las' time I saw you, you was only a baby,\" said the giant. \"Yeh look a\nlot like yet dad, but yeh've got yet mom's eyes.\"\n\nUncle Vernon made a funny rasping noise.\n\nI demand that you leave at once, sit!\" he said. \"You are breaking and\nentering!\"\n\n\"Ah, shut up, Dursley, yeh great prune,\" said the giant; he reached over\nthe back of the sofa, jerked the gun out of Uncle Vernon's hands, bent\nit into a knot as easily as if it had been made of rubber, and threw it\ninto a corner of the room.\n\nUncle Vernon made another funny noise, like a mouse being trodden on.\n\n\"Anyway -- Harry,\" said the giant, turning his back on the Dursleys, \"a\nvery happy birthday to yeh. Got summat fer yeh here -- I mighta sat on\nit at some point, but it'll taste all right.\"\n\nFrom an inside pocket of his black overcoat he pulled a slightly\nsquashed box. Harry opened it with trembling fingers. Inside was a\nlarge, sticky chocolate cake with Happy Birthday Harry written on it in\ngreen icing.\n\nHarry looked up at the giant. He meant to say thank you, but the words\ngot lost on the way to his mouth, and what he said instead was, \"Who are\nyou?\"\n\nThe giant chuckled.\n\n\"True, I haven't introduced meself. Rubeus Hagrid, Keeper of Keys and\nGrounds at Hogwarts.\"\n\nHe held out an enormous hand and shook Harry's whole arm.\n\n\"What about that tea then, eh?\" he said, rubbing his hands together.\n\"I'd not say no ter summat stronger if yeh've got it, mind.\"\n\nHis eyes fell on the empty grate with the shriveled chip bags in it and\nhe snorted. He bent down over the fireplace; they couldn't see what he\nwas doing but when he drew back a second later, there was a roaring fire\nthere. It filled the whole damp hut with flickering light and Harry felt\nthe warmth wash over him as though he'd sunk into a hot bath.\n\nThe giant sat back down on the sofa, which sagged under his weight, and\nbegan taking all sorts of things out of the pockets of his coat: a\ncopper kettle, a squashy package of sausages, a poker, a teapot, several\nchipped mugs, and a bottle of some amber liquid that he took a swig from\nbefore starting to make tea. Soon the hut was full of the sound and\nsmell of sizzling sausage. Nobody said a thing while the giant was\nworking, but as he slid the first six fat, juicy, slightly burnt\nsausages from the poker, Dudley fidgeted a little. Uncle Vernon said\nsharply, \"Don't touch anything he gives you, Dudley.\"\n\nThe giant chuckled darkly.\n\n\"Yet great puddin' of a son don' need fattenin' anymore, Dursley, don'\nworry.\"\n\nHe passed the sausages to Harry, who was so hungry he had never tasted\nanything so wonderful, but he still couldn't take his eyes off the\ngiant. Finally, as nobody seemed about to explain anything, he said,\n\"I'm sorry, but I still don't really know who you are.\"\n\nThe giant took a gulp of tea and wiped his mouth with the back of his\nhand.\n\n\"Call me Hagrid,\" he said, \"everyone does. An' like I told yeh, I'm\nKeeper of Keys at Hogwarts -- yeh'll know all about Hogwarts, o' course.\n\n\"Er -- no,\" said Harry.\n\nHagrid looked shocked.\n\n\"Sorry,\" Harry said quickly.\n\n\"Sony?\" barked Hagrid, turning to stare at the Dursleys, who shrank back\ninto the shadows. \"It' s them as should be sorry! I knew yeh weren't\ngettin' yer letters but I never thought yeh wouldn't even know abou'\nHogwarts, fer cryin' out loud! Did yeh never wonder where yet parents\nlearned it all?\"\n\n\"All what?\" asked Harry.\n\n\"ALL WHAT?\" Hagrid thundered. \"Now wait jus' one second!\"\n\nHe had leapt to his feet. In his anger he seemed to fill the whole hut.\nThe Dursleys were cowering against the wall.\n\n\"Do you mean ter tell me,\" he growled at the Dursleys, \"that this boy --\nthis boy! -- knows nothin' abou' -- about ANYTHING?\"\n\nHarry"
    }
}
{
    "type": "error",
    "data": "Entity Extraction Error",
    "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 122, in __call__\n    result = await self._process_document(text, prompt_variables)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 161, in _process_document\n    response = await self._llm(\n               ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\json_parsing_llm.py\", line 34, in __call__\n    result = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_token_replacing_llm.py\", line 37, in __call__\n    return await self._delegate(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_history_tracking_llm.py\", line 33, in __call__\n    output = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\caching_llm.py\", line 96, in __call__\n    result = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 177, in __call__\n    result, start = await execute_with_retry()\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 159, in execute_with_retry\n    async for attempt in retryer:\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 166, in __anext__\n    do = await self.iter(retry_state=self._retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 153, in iter\n    result = await action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\_utils.py\", line 99, in inner\n    return call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\__init__.py\", line 418, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\__init__.py\", line 185, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\concurrent\\futures\\_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\concurrent\\futures\\_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 165, in execute_with_retry\n    return await do_attempt(), start\n           ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 151, in do_attempt\n    await sleep_for(sleep_time)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 147, in do_attempt\n    return await self._delegate(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 50, in __call__\n    return await self._invoke(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 54, in _invoke\n    output = await self._execute_llm(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_chat_llm.py\", line 53, in _execute_llm\n    completion = await self.client.chat.completions.create(\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\resources\\chat\\completions.py\", line 1661, in create\n    return await self._post(\n           ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1839, in post\n    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1533, in request\n    return await self._request(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1634, in _request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 198473, Requested 7461. Please try again in 1.78s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}\n",
    "source": "Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 198473, Requested 7461. Please try again in 1.78s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}",
    "details": {
        "doc_index": 0,
        "text": "and then forced his face into a\nsmile, which looked quite painful.\n\n\"Er -- yes, Harry -- about this cupboard. Your aunt and I have been\nthinking... you're really getting a bit big for it... we think it might\nbe nice if you moved into Dudley's second bedroom.\n\n\"Why?\" said Harry.\n\n\"Don't ask questions!\" snapped his uncle. \"Take this stuff upstairs,\nnow.\"\n\nThe Dursleys' house had four bedrooms: one for Uncle Vernon and Aunt\nPetunia, one for visitors (usually Uncle Vernon's sister, Marge), one\nwhere Dudley slept, and one where Dudley kept all the toys and things\nthat wouldn't fit into his first bedroom. It only took Harry one trip\nupstairs to move everything he owned from the cupboard to this room. He\nsat down on the bed and stared around him. Nearly everything in here was\nbroken. The month-old video camera was lying on top of a small, working\ntank Dudley had once driven over the next door neighbor's dog; in the\ncorner was Dudley's first-ever television set, which he'd put his foot\nthrough when his favorite program had been canceled; there was a large\nbirdcage, which had once held a parrot that Dudley had swapped at school\nfor a real air rifle, which was up on a shelf with the end all bent\nbecause Dudley had sat on it. Other shelves were full of books. They\nwere the only things in the room that looked as though they'd never been\ntouched.\n\nFrom downstairs came the sound of Dudley bawling at his mother, I don't\nwant him in there... I need that room... make him get out....\"\n\nHarry sighed and stretched out on the bed. Yesterday he'd have given\nanything to be up here. Today he'd rather be back in his cupboard with\nthat letter than up here without it.\n\nNext morning at breakfast, everyone was rather quiet. Dudley was in\nshock. He'd screamed, whacked his father with his Smelting stick, been\nsick on purpose, kicked his mother, and thrown his tortoise through the\ngreenhouse roof, and he still didn't have his room back. Harry was\nthinking about this time yesterday and bitterly wishing he'd opened the\nletter in the hall. Uncle Vernon and Aunt Petunia kept looking at each\nother darkly.\n\nWhen the mail arrived, Uncle Vernon, who seemed to be trying to be nice\nto Harry, made Dudley go and get it. They heard him banging things with\nhis Smelting stick all the way down the hall. Then he shouted, \"There's\nanother one! 'Mr. H. Potter, The Smallest Bedroom, 4 Privet Drive --'\"\n\nWith a strangled cry, Uncle Vernon leapt from his seat and ran down the\nhall, Harry right behind him. Uncle Vernon had to wrestle Dudley to the\nground to get the letter from him, which was made difficult by the fact\nthat Harry had grabbed Uncle Vernon around the neck from behind. After a\nminute of confused fighting, in which everyone got hit a lot by the\nSmelting stick, Uncle Vernon straightened up, gasping for breath, with\nHarry's letter clutched in his hand.\n\n\"Go to your cupboard -- I mean, your bedroom,\" he wheezed at Harry.\n\"Dudley -- go -- just go.\"\n\nHarry walked round and round his new room. Someone knew he had moved out\nof his cupboard and they seemed to know he hadn't received his first\nletter. Surely that meant they'd try again? And this time he'd make sure\nthey didn't fail. He had a plan.\n\nThe repaired alarm clock rang at six o'clock the next morning. Harry\nturned it off quickly and dressed silently. He mustn't wake the\nDursleys. He stole downstairs without turning on any of the lights.\n\nHe was going to wait for the postman on the corner of Privet Drive and\nget the letters for number four first. His heart hammered as he crept\nacross the dark hall toward the front door --\n\nHarry leapt into the air; he'd trodden on something big and squashy on\nthe doormat -- something alive!\n\nLights clicked on upstairs and to his horror Harry realized that the\nbig, squashy something had been his uncle's face. Uncle Vernon had been\nlying at the foot of the front door in a sleeping bag, clearly making\nsure that Harry didn't do exactly what he'd been trying to do. He\nshouted at Harry for about half an hour and then told him to go and make\na cup of tea. Harry shuffled miserably off into the kitchen and by the\ntime he got back, the mail had arrived, right into Uncle Vernon's lap.\nHarry could see three letters addressed in green ink.\n\nI want --\" he began, but Uncle Vernon was tearing the letters into\npieces before his eyes. Uncle Vernon didnt go to work that day. He\nstayed at home and nailed up the mail slot.\n\n\"See,\" he explained to Aunt Petunia through a mouthful of nails, \"if\nthey can't deliver them they'll just give up.\"\n\n\"I'm not sure that'll work, Vernon.\"\n\n\"Oh, these people's minds work in strange ways, Petunia, they're not\nlike you and me,\" said Uncle Vernon, trying to knock in a nail with the\npiece of fruitcake Aunt Petunia had just brought him.\n\nOn Friday, no less than twelve letters arrived for Harry. As they\ncouldn't go through the mail slot they had been pushed under the door,\nslotted through the sides, and a few even forced through the small\nwindow in the downstairs bathroom.\n\nUncle Vernon stayed at home again."
    }
}
{
    "type": "error",
    "data": "Entity Extraction Error",
    "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 122, in __call__\n    result = await self._process_document(text, prompt_variables)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 161, in _process_document\n    response = await self._llm(\n               ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\json_parsing_llm.py\", line 34, in __call__\n    result = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_token_replacing_llm.py\", line 37, in __call__\n    return await self._delegate(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_history_tracking_llm.py\", line 33, in __call__\n    output = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\caching_llm.py\", line 96, in __call__\n    result = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 177, in __call__\n    result, start = await execute_with_retry()\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 159, in execute_with_retry\n    async for attempt in retryer:\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 166, in __anext__\n    do = await self.iter(retry_state=self._retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 153, in iter\n    result = await action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\_utils.py\", line 99, in inner\n    return call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\__init__.py\", line 418, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\__init__.py\", line 185, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\concurrent\\futures\\_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\concurrent\\futures\\_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 165, in execute_with_retry\n    return await do_attempt(), start\n           ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 151, in do_attempt\n    await sleep_for(sleep_time)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 147, in do_attempt\n    return await self._delegate(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 50, in __call__\n    return await self._invoke(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 54, in _invoke\n    output = await self._execute_llm(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_chat_llm.py\", line 53, in _execute_llm\n    completion = await self.client.chat.completions.create(\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\resources\\chat\\completions.py\", line 1661, in create\n    return await self._post(\n           ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1839, in post\n    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1533, in request\n    return await self._request(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1634, in _request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 196191, Requested 7674. Please try again in 1.159s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}\n",
    "source": "Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 196191, Requested 7674. Please try again in 1.159s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}",
    "details": {
        "doc_index": 0,
        "text": "next lamp flickered into darkness. Twelve times\nhe clicked the Put-Outer, until the only lights left on the whole street\nwere two tiny pinpricks in the distance, which were the eyes of the cat\nwatching him. If anyone looked out of their window now, even beady-eyed\nMrs. Dursley, they wouldn't be able to see anything that was happening\ndown on the pavement. Dumbledore slipped the Put-Outer back inside his\ncloak and set off down the street toward number four, where he sat down\non the wall next to the cat. He didn't look at it, but after a moment he\nspoke to it.\n\n\"Fancy seeing you here, Professor McGonagall.\"\n\nHe turned to smile at the tabby, but it had gone. Instead he was smiling\nat a rather severe-looking woman who was wearing square glasses exactly\nthe shape of the markings the cat had had around its eyes. She, too, was\nwearing a cloak, an emerald one. Her black hair was drawn into a tight\nbun. She looked distinctly ruffled.\n\n\"How did you know it was me?\" she asked.\n\n\"My dear Professor, I 've never seen a cat sit so stiffly.\"\n\n\"You'd be stiff if you'd been sitting on a brick wall all day,\" said\nProfessor McGonagall.\n\n\"All day? When you could have been celebrating? I must have passed a\ndozen feasts and parties on my way here.\"\n\nProfessor McGonagall sniffed angrily.\n\n\"Oh yes, everyone's celebrating, all right,\" she said impatiently.\n\"You'd think they'd be a bit more careful, but no -- even the Muggles\nhave noticed something's going on. It was on their news.\" She jerked her\nhead back at the Dursleys' dark living-room window. \"I heard it. Flocks\nof owls... shooting stars.... Well, they're not completely stupid. They\nwere bound to notice something. Shooting stars down in Kent -- I'll bet\nthat was Dedalus Diggle. He never had much sense.\"\n\n\"You can't blame them,\" said Dumbledore gently. \"We've had precious\nlittle to celebrate for eleven years.\"\n\n\"I know that,\" said Professor McGonagall irritably. \"But that's no\nreason to lose our heads. People are being downright careless, out on\nthe streets in broad daylight, not even dressed in Muggle clothes,\nswapping rumors.\"\n\nShe threw a sharp, sideways glance at Dumbledore here, as though hoping\nhe was going to tell her something, but he didn't, so she went on. \"A\nfine thing it would be if, on the very day YouKnow-Who seems to have\ndisappeared at last, the Muggles found out about us all. I suppose he\nreally has gone, Dumbledore?\"\n\n\"It certainly seems so,\" said Dumbledore. \"We have much to be thankful\nfor. Would you care for a lemon drop?\"\n\n\"A what?\"\n\n\"A lemon drop. They're a kind of Muggle sweet I'm rather fond of\"\n\n\"No, thank you,\" said Professor McGonagall coldly, as though she didn't\nthink this was the moment for lemon drops. \"As I say, even if\nYou-Know-Who has gone -\"\n\n\"My dear Professor, surely a sensible person like yourself can call him\nby his name? All this 'You- Know-Who' nonsense -- for eleven years I\nhave been trying to persuade people to call him by his proper name:\nVoldemort.\" Professor McGonagall flinched, but Dumbledore, who was\nunsticking two lemon drops, seemed not to notice. \"It all gets so\nconfusing if we keep saying 'You-Know-Who.' I have never seen any reason\nto be frightened of saying Voldemort's name.\n\n\"I know you haven 't, said Professor McGonagall, sounding half\nexasperated, half admiring. \"But you're different. Everyone knows you're\nthe only one You-Know- oh, all right, Voldemort, was frightened of.\"\n\n\"You flatter me,\" said Dumbledore calmly. \"Voldemort had powers I will\nnever have.\"\n\n\"Only because you're too -- well -- noble to use them.\"\n\n\"It's lucky it's dark. I haven't blushed so much since Madam Pomfrey\ntold me she liked my new earmuffs.\"\n\nProfessor McGonagall shot a sharp look at Dumbledore and said, \"The owls\nare nothing next to the rumors that are flying around. You know what\neveryone's saying? About why he's disappeared? About what finally\nstopped him?\"\n\nIt seemed that Professor McGonagall had reached the point she was most\nanxious to discuss, the real reason she had been waiting on a cold, hard\nwall all day, for neither as a cat nor as a woman had she fixed\nDumbledore with such a piercing stare as she did now. It was plain that\nwhatever \"everyone\" was saying, she was not going to believe it until\nDumbledore told her it was true. Dumbledore, however, was choosing\nanother lemon drop and did not answer.\n\n\"What they're saying,\" she pressed on, \"is that last night Voldemort\nturned up in Godric's Hollow. He went to find the Potters. The rumor is\nthat Lily and James Potter are -- are -- that they're -- dead. \"\n\nDumbledore bowed his head. Professor McGonagall gasped.\n\n\"Lily and James... I can't believe it... I didn't want to believe it...\nOh, Albus...\"\n\nDumbledore reached out and patted her on the shoulder. \"I know... I\nknow...\" he said heavily.\n\nProfessor McGonagall's voice trembled as she went"
    }
}
{
    "type": "error",
    "data": "Entity Extraction Error",
    "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 122, in __call__\n    result = await self._process_document(text, prompt_variables)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 161, in _process_document\n    response = await self._llm(\n               ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\json_parsing_llm.py\", line 34, in __call__\n    result = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_token_replacing_llm.py\", line 37, in __call__\n    return await self._delegate(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_history_tracking_llm.py\", line 33, in __call__\n    output = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\caching_llm.py\", line 96, in __call__\n    result = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 177, in __call__\n    result, start = await execute_with_retry()\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 159, in execute_with_retry\n    async for attempt in retryer:\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 166, in __anext__\n    do = await self.iter(retry_state=self._retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 153, in iter\n    result = await action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\_utils.py\", line 99, in inner\n    return call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\__init__.py\", line 418, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\__init__.py\", line 185, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\concurrent\\futures\\_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\concurrent\\futures\\_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 165, in execute_with_retry\n    return await do_attempt(), start\n           ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 151, in do_attempt\n    await sleep_for(sleep_time)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 147, in do_attempt\n    return await self._delegate(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 50, in __call__\n    return await self._invoke(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 54, in _invoke\n    output = await self._execute_llm(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_chat_llm.py\", line 53, in _execute_llm\n    completion = await self.client.chat.completions.create(\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\resources\\chat\\completions.py\", line 1661, in create\n    return await self._post(\n           ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1839, in post\n    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1533, in request\n    return await self._request(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1634, in _request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 195254, Requested 7490. Please try again in 823ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}\n",
    "source": "Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 195254, Requested 7490. Please try again in 823ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}",
    "details": {
        "doc_index": 0,
        "text": "itself -- no\ncompany except stupid people drumming their fingers on the glass trying\nto disturb it all day long. It was worse than having a cupboard as a\nbedroom, where the only visitor was Aunt Petunia hammering on the door\nto wake you up; at least he got to visit the rest of the house.\n\nThe snake suddenly opened its beady eyes. Slowly, very slowly, it raised\nits head until its eyes were on a level with Harry's.\n\nIt winked.\n\nHarry stared. Then he looked quickly around to see if anyone was\nwatching. They weren't. He looked back at the snake and winked, too.\n\nThe snake jerked its head toward Uncle Vernon and Dudley, then raised\nits eyes to the ceiling. It gave Harry a look that said quite plainly:\n\n\"I get that all the time.\n\n\"I know,\" Harry murmured through the glass, though he wasn't sure the\nsnake could hear him. \"It must be really annoying.\"\n\nThe snake nodded vigorously.\n\n\"Where do you come from, anyway?\" Harry asked.\n\nThe snake jabbed its tail at a little sign next to the glass. Harry\npeered at it.\n\nBoa Constrictor, Brazil.\n\n\"Was it nice there?\"\n\nThe boa constrictor jabbed its tail at the sign again and Harry read on:\nThis specimen was bred in the zoo. \"Oh, I see -- so you've never been to\nBrazil?\"\n\nAs the snake shook its head, a deafening shout behind Harry made both of\nthem jump.\n\n\"DUDLEY! MR. DURSLEY! COME AND LOOK AT THIS SNAKE! YOU WON'T BELIEVE\nWHAT IT'S DOING!\"\n\nDudley came waddling toward them as fast as he could.\n\n\"Out of the way, you,\" he said, punching Harry in the ribs. Caught by\nsurprise, Harry fell hard on the concrete floor. What came next happened\nso fast no one saw how it happened -- one second, Piers and Dudley were\nleaning right up close to the glass, the next, they had leapt back with\nhowls of horror.\n\nHarry sat up and gasped; the glass front of the boa constrictor's tank\nhad vanished. The great snake was uncoiling itself rapidly, slithering\nout onto the floor. People throughout the reptile house screamed and\nstarted running for the exits.\n\nAs the snake slid swiftly past him, Harry could have sworn a low,\nhissing voice said, \"Brazil, here I come.... Thanksss, amigo.\"\n\nThe keeper of the reptile house was in shock.\n\n\"But the glass,\" he kept saying, \"where did the glass go?\"\n\nThe zoo director himself made Aunt Petunia a cup of strong, sweet tea\nwhile he apologized over and over again. Piers and Dudley could only\ngibber. As far as Harry had seen, the snake hadn't done anything except\nsnap playfully at their heels as it passed, but by the time they were\nall back in Uncle Vernon's car, Dudley was telling them how it had\nnearly bitten off his leg, while Piers was swearing it had tried to\nsqueeze him to death. But worst of all, for Harry at least, was Piers\ncalming down enough to say, \"Harry was talking to it, weren't you,\nHarry?\"\n\nUncle Vernon waited until Piers was safely out of the house before\nstarting on Harry. He was so angry he could hardly speak. He managed to\nsay, \"Go -- cupboard -- stay -- no meals,\" before he collapsed into a\nchair, and Aunt Petunia had to run and get him a large brandy.\n\nHarry lay in his dark cupboard much later, wishing he had a watch. He\ndidn't know what time it was and he couldn't be sure the Dursleys were\nasleep yet. Until they were, he couldn't risk sneaking to the kitchen\nfor some food.\n\nHe'd lived with the Dursleys almost ten years, ten miserable years, as\nlong as he could remember, ever since he'd been a baby and his parents\nhad died in that car crash. He couldn't remember being in the car when\nhis parents had died. Sometimes, when he strained his memory during long\nhours in his cupboard, he came up with a strange vision: a blinding\nflash of green light and a burn- ing pain on his forehead. This, he\nsupposed, was the crash, though he couldn't imagine where all the green\nlight came from. He couldn't remember his parents at all. His aunt and\nuncle never spoke about them, and of course he was forbidden to ask\nquestions. There were no photographs of them in the house.\n\nWhen he had been younger, Harry had dreamed and dreamed of some unknown\nrelation coming to take him away, but it had never happened; the\nDursleys were his only family. Yet sometimes he thought (or maybe hoped)\nthat strangers in the street seemed to know him. Very strange strangers\nthey were, too. A tiny man in a violet top hat had bowed to him once\nwhile out shopping with Aunt Petunia and Dudley. After asking Harry\nfuriously if he knew the man, Aunt Petunia had rushed them out of the\nshop without buying anything. A wild-looking old woman dressed all in\ngreen had waved merrily at him once on a bus. A bald man in a very long\npurple coat had actually shaken his hand in the street the other day and\nthen walked away without a word. The weirdest thing about all these\npeople was the way they seemed to vanish the second Harry tried to get a\ncloser look.\n\nAt school, Harry had no one. Everybody knew that Dudley's"
    }
}
{
    "type": "error",
    "data": "Entity Extraction Error",
    "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 122, in __call__\n    result = await self._process_document(text, prompt_variables)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 161, in _process_document\n    response = await self._llm(\n               ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\json_parsing_llm.py\", line 34, in __call__\n    result = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_token_replacing_llm.py\", line 37, in __call__\n    return await self._delegate(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_history_tracking_llm.py\", line 33, in __call__\n    output = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\caching_llm.py\", line 96, in __call__\n    result = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 177, in __call__\n    result, start = await execute_with_retry()\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 159, in execute_with_retry\n    async for attempt in retryer:\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 166, in __anext__\n    do = await self.iter(retry_state=self._retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 153, in iter\n    result = await action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\_utils.py\", line 99, in inner\n    return call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\__init__.py\", line 418, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\__init__.py\", line 185, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\concurrent\\futures\\_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\concurrent\\futures\\_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 165, in execute_with_retry\n    return await do_attempt(), start\n           ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 151, in do_attempt\n    await sleep_for(sleep_time)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 147, in do_attempt\n    return await self._delegate(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 50, in __call__\n    return await self._invoke(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 54, in _invoke\n    output = await self._execute_llm(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_chat_llm.py\", line 53, in _execute_llm\n    completion = await self.client.chat.completions.create(\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\resources\\chat\\completions.py\", line 1661, in create\n    return await self._post(\n           ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1839, in post\n    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1533, in request\n    return await self._request(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1634, in _request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 198683, Requested 7455. Please try again in 1.841s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}\n",
    "source": "Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 198683, Requested 7455. Please try again in 1.841s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}",
    "details": {
        "doc_index": 0,
        "text": "where yet parents\nlearned it all?\"\n\n\"All what?\" asked Harry.\n\n\"ALL WHAT?\" Hagrid thundered. \"Now wait jus' one second!\"\n\nHe had leapt to his feet. In his anger he seemed to fill the whole hut.\nThe Dursleys were cowering against the wall.\n\n\"Do you mean ter tell me,\" he growled at the Dursleys, \"that this boy --\nthis boy! -- knows nothin' abou' -- about ANYTHING?\"\n\nHarry thought this was going a bit far. He had been to school, after\nall, and his marks weren't bad.\n\n\"I know some things,\" he said. \"I can, you know, do math and stuff.\" But\nHagrid simply waved his hand and said, \"About our world, I mean. Your\nworld. My world. Yer parents' world.\"\n\n\"What world?\"\n\nHagrid looked as if he was about to explode.\n\n\"DURSLEY!\" he boomed.\n\nUncle Vernon, who had gone very pale, whispered something that sounded\nlike \"Mimblewimble.\" Hagrid stared wildly at Harry.\n\n\"But yeh must know about yet mom and dad,\" he said. \"I mean, they're\nfamous. You're famous.\"\n\n\"What? My -- my mom and dad weren't famous, were they?\"\n\n\"Yeh don' know... yeh don' know...\" Hagrid ran his fingers through his\nhair, fixing Harry with a bewildered stare.\n\n\"Yeh don' know what yeh are?\" he said finally.\n\nUncle Vernon suddenly found his voice.\n\n\"Stop!\" he commanded. \"Stop right there, sit! I forbid you to tell the\nboy anything!\"\n\nA braver man than Vernon Dursley would have quailed under the furious\nlook Hagrid now gave him; when Hagrid spoke, his every syllable trembled\nwith rage.\n\n\"You never told him? Never told him what was in the letter Dumbledore\nleft fer him? I was there! I saw Dumbledore leave it, Dursley! An'\nyou've kept it from him all these years?\"\n\n\"Kept what from me?\" said Harry eagerly.\n\n\"STOP! I FORBID YOU!\" yelled Uncle Vernon in panic.\n\nAunt Petunia gave a gasp of horror.\n\n\"Ah, go boil yet heads, both of yeh,\" said Hagrid. \"Harry -- yet a\nwizard.\"\n\nThere was silence inside the hut. Only the sea and the whistling wind\ncould be heard.\n\n\"-- a what?\" gasped Harry.\n\n\"A wizard, o' course,\" said Hagrid, sitting back down on the sofa, which\ngroaned and sank even lower, \"an' a thumpin' good'un, I'd say, once\nyeh've been trained up a bit. With a mum an' dad like yours, what else\nwould yeh be? An' I reckon it's abou' time yeh read yer letter.\"\n\nHarry stretched out his hand at last to take the yellowish envelope,\naddressed in emerald green to Mr. H. Potter, The Floor, Hut-on-the-Rock,\nThe Sea. He pulled out the letter and read:\n\nHOGWARTS SCHOOL of WITCHCRAFT and WIZARDRY\n\nHeadmaster: ALBUS DUMBLEDORE\n\n(Order of Merlin, First Class, Grand Sorc., Chf. Warlock, Supreme\nMugwump, International Confed. of Wizards)\n\nDear Mr. Potter,\n\nWe are pleased to inform you that you have been accepted at Hogwarts\nSchool of Witchcraft and Wizardry. Please find enclosed a list of all\nnecessary books and equipment.\n\nTerm begins on September 1. We await your owl by no later than July 31.\nYours sincerely,\n\nMinerva McGonagall,\n\nDeputy Headmistress\n\nQuestions exploded inside Harry's head like fireworks and he couldn't\ndecide which to ask first. After a few minutes he stammered, \"What does\nit mean, they await my owl?\"\n\n\"Gallopin' Gorgons, that reminds me,\" said Hagrid, clapping a hand to\nhis forehead with enough force to knock over a cart horse, and from yet\nanother pocket inside his overcoat he pulled an owl -- a real, live,\nrather ruffled-looking owl -- a long quill, and a roll of parchment.\nWith his tongue between his teeth he scribbled a note that Harry could\nread upside down:\n\nDear Professor Dumbledore,\n\nGiven Harry his letter.\n\nTaking him to buy his things tomorrow.\n\nWeather's horrible. Hope you're Well.\n\nHagrid\n\nHagrid rolled up the note, gave it to the owl, which clamped it in its\nbeak, went to the door, and threw the owl out into the storm. Then he\ncame back and sat down as though this was as normal as talking on the\ntelephone.\n\nHarry realized his mouth was open and closed it quickly.\n\n\"Where was I?\" said Hagrid, but at that moment, Uncle Vernon, still\nashen-faced but looking very angry, moved into the firelight.\n\n\"He's not going,\" he said.\n\nHagrid grunted.\n\n\"I'd like ter see a great Muggle like you stop him,\" he said.\n\n\"A what?\" said Harry, interested.\n\n\"A Muggle,\" said Hagrid, \"it's what we call nonmagic folk like thern.\nAn' it's your bad luck you grew up in a family o' the biggest Muggles I\never laid eyes on.\"\n\n\"We swore when we took him in we'd put a stop to that rubbish,\" said\nUncle Vernon, \"swore we'd stamp it out of him! Wizard indeed!\"\n\n\"You knew?\" said Harry. \"You knew I'm a -- a wizard?\"\n\n\"Knew!\""
    }
}
{
    "type": "error",
    "data": "Entity Extraction Error",
    "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 122, in __call__\n    result = await self._process_document(text, prompt_variables)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 161, in _process_document\n    response = await self._llm(\n               ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\json_parsing_llm.py\", line 34, in __call__\n    result = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_token_replacing_llm.py\", line 37, in __call__\n    return await self._delegate(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_history_tracking_llm.py\", line 33, in __call__\n    output = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\caching_llm.py\", line 96, in __call__\n    result = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 177, in __call__\n    result, start = await execute_with_retry()\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 159, in execute_with_retry\n    async for attempt in retryer:\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 166, in __anext__\n    do = await self.iter(retry_state=self._retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 153, in iter\n    result = await action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\_utils.py\", line 99, in inner\n    return call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\__init__.py\", line 418, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\__init__.py\", line 185, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\concurrent\\futures\\_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\concurrent\\futures\\_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 165, in execute_with_retry\n    return await do_attempt(), start\n           ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 151, in do_attempt\n    await sleep_for(sleep_time)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 147, in do_attempt\n    return await self._delegate(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 50, in __call__\n    return await self._invoke(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 54, in _invoke\n    output = await self._execute_llm(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_chat_llm.py\", line 53, in _execute_llm\n    completion = await self.client.chat.completions.create(\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\resources\\chat\\completions.py\", line 1661, in create\n    return await self._post(\n           ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1839, in post\n    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1533, in request\n    return await self._request(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1634, in _request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 194072, Requested 7634. Please try again in 511ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}\n",
    "source": "Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 194072, Requested 7634. Please try again in 511ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}",
    "details": {
        "doc_index": 0,
        "text": "else for it.\n\n\"Excuse me,\" Harry said to the plump woman.\n\n\"Hello, dear,\" she said. \"First time at Hogwarts? Ron's new, too.\"\n\nShe pointed at the last and youngest of her sons. He was tall, thin, and\ngangling, with freckles, big hands and feet, and a long nose.\n\n\"Yes,\" said Harry. \"The thing is -- the thing is, I don't know how to\n--\"\n\n\"How to get onto the platform?\" she said kindly, and Harry nodded.\n\n\"Not to worry,\" she said. \"All you have to do is walk straight at the\nbarrier between platforms nine and ten. Don't stop and don't be scared\nyou'll crash into it, that's very important. Best do it at a bit of a\nrun if you're nervous. Go on, go now before Ron.\"\n\n\"Er -- okay,\" said Harry.\n\nHe pushed his trolley around and stared at the barrier. It looked very\nsolid.\n\nHe started to walk toward it. People jostled him on their way to\nplatforms nine and ten. Harry walked more quickly. He was going to smash\nright into that barrier and then he'd be in trouble -- leaning forward\non his cart, he broke into a heavy run -- the barrier was coming nearer\nand nearer -- he wouldn't be able to stop -- the cart was out of control\n-- he was a foot away -- he closed his eyes ready for the crash --\n\nIt didn't come... he kept on running... he opened his eyes. A scarlet\nsteam engine was waiting next to a platform packed with people. A sign\noverhead said Hogwarts Express, eleven O'clock. Harry looked behind him\nand saw a wrought-iron archway where the barrier had been, with the\nwords Platform Nine and Three-Quarters on it, He had done it.\n\nSmoke from the engine drifted over the heads of the chattering crowd,\nwhile cats of every color wound here and there between their legs. Owls\nhooted to one another in a disgruntled sort of way over the babble and\nthe scraping of heavy trunks.\n\nThe first few carriages were already packed with students, some hanging\nout of the window to talk to their families, some fighting over seats.\nHarry pushed his cart off down the platform in search of an empty seat.\nHe passed a round-faced boy who was saying, \"Gran, I've lost my toad\nagain.\"\n\n\"Oh, Neville,\" he heard the old woman sigh.\n\nA boy with dreadlocks was surrounded by a small crowd.\n\n\"Give us a look, Lee, go on.\"\n\nThe boy lifted the lid of a box in his arms, and the people around him\nshrieked and yelled as something inside poked out a long, hairy leg.\n\nHarry pressed on through the crowd until he found an empty compartment\nnear the end of the train. He put Hedwig inside first and then started\nto shove and heave his trunk toward the train door. He tried to lift it\nup the steps but could hardly raise one end and twice he dropped it\npainfully on his foot.\n\n\"Want a hand?\" It was one of the red-haired twins he'd followed through\nthe barrier.\n\n\"Yes, please,\" Harry panted.\n\n\"Oy, Fred! C'mere and help!\"\n\nWith the twins' help, Harry's trunk was at last tucked away in a corner\nof the compartment.\n\n\"Thanks,\" said Harry, pushing his sweaty hair out of his eyes.\n\n\"What's that?\" said one of the twins suddenly, pointing at Harry's\nlightning scar.\n\n\"Blimey,\" said the other twin. \"Are you\n\n\"He is,\" said the first twin. \"Aren't you?\" he added to Harry.\n\n\"What?\" said Harry.\n\n\"Harry Potter, \"chorused the twins.\n\n\"Oh, him,\" said Harry. \"I mean, yes, I am.\"\n\nThe two boys gawked at him, and Harry felt himself turning red. Then, to\nhis relief, a voice came floating in through the train's open door.\n\n\"Fred? George? Are you there?\"\n\n\"Coming, Mom.\"\n\nWith a last look at Harry, the twins hopped off the train.\n\nHarry sat down next to the window where, half hidden, he could watch the\nred-haired family on the platform and hear what they were saying. Their\nmother had just taken out her handkerchief.\n\n\"Ron, you've got something on your nose.\"\n\nThe youngest boy tried to jerk out of the way, but she grabbed him and\nbegan rubbing the end of his nose.\n\n\"Mom -- geroff\" He wriggled free.\n\n\"Aaah, has ickle Ronnie got somefink on his nosie?\" said one of the\ntwins.\n\n\"Shut up,\" said Ron.\n\n\"Where's Percy?\" said their mother.\n\n\"He's coming now.\"\n\nThe oldest boy came striding into sight. He had already changed into his\nbillowing black Hogwarts robes, and Harry noticed a shiny silver badge\non his chest with the letter P on it.\n\n\"Can't stay long, Mother,\" he said. \"I'm up front, the prefects have got\ntwo compartments to themselves --\"\n\n\"Oh, are you a prefect, Percy?\" said one of the twins, with an air of\ngreat surprise. \"You should have said something, we had no idea.\"\n\n\"Hang on, I think I remember him saying something about it,\" said the\nother twin. \"Once --\"\n\n\"Or twice --\"\n\n\"A minute --\"\n\n\"All summer --\"\n\n\"Oh, shut up,\" said Percy the Prefect.\n\n\"How come Percy gets new robes, anyway?\" said one of the twins.\n\n\"Because he's a prefect,\" said their mother fondly. \"All right, dear"
    }
}
{
    "type": "error",
    "data": "Entity Extraction Error",
    "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 122, in __call__\n    result = await self._process_document(text, prompt_variables)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 161, in _process_document\n    response = await self._llm(\n               ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\json_parsing_llm.py\", line 34, in __call__\n    result = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_token_replacing_llm.py\", line 37, in __call__\n    return await self._delegate(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_history_tracking_llm.py\", line 33, in __call__\n    output = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\caching_llm.py\", line 96, in __call__\n    result = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 177, in __call__\n    result, start = await execute_with_retry()\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 159, in execute_with_retry\n    async for attempt in retryer:\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 166, in __anext__\n    do = await self.iter(retry_state=self._retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 153, in iter\n    result = await action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\_utils.py\", line 99, in inner\n    return call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\__init__.py\", line 418, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\__init__.py\", line 185, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\concurrent\\futures\\_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\concurrent\\futures\\_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 165, in execute_with_retry\n    return await do_attempt(), start\n           ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 151, in do_attempt\n    await sleep_for(sleep_time)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 147, in do_attempt\n    return await self._delegate(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 50, in __call__\n    return await self._invoke(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 54, in _invoke\n    output = await self._execute_llm(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_chat_llm.py\", line 53, in _execute_llm\n    completion = await self.client.chat.completions.create(\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\resources\\chat\\completions.py\", line 1661, in create\n    return await self._post(\n           ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1839, in post\n    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1533, in request\n    return await self._request(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1634, in _request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 194859, Requested 7488. Please try again in 704ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}\n",
    "source": "Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 194859, Requested 7488. Please try again in 704ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}",
    "details": {
        "doc_index": 0,
        "text": "an air of\ngreat surprise. \"You should have said something, we had no idea.\"\n\n\"Hang on, I think I remember him saying something about it,\" said the\nother twin. \"Once --\"\n\n\"Or twice --\"\n\n\"A minute --\"\n\n\"All summer --\"\n\n\"Oh, shut up,\" said Percy the Prefect.\n\n\"How come Percy gets new robes, anyway?\" said one of the twins.\n\n\"Because he's a prefect,\" said their mother fondly. \"All right, dear,\nwell, have a good term -- send me an owl when you get there.\"\n\nShe kissed Percy on the cheek and he left. Then she turned to the twins.\n\n\"Now, you two -- this year, you behave yourselves. If I get one more owl\ntelling me you've -- you've blown up a toilet or --\"\n\n\"Blown up a toilet? We've never blown up a toilet.\"\n\n\"Great idea though, thanks, Mom.\"\n\n\"It's not funny. And look after Ron.\"\n\n\"Don't worry, ickle Ronniekins is safe with us.\"\n\n\"Shut up,\" said Ron again. He was almost as tall as the twins already\nand his nose was still pink where his mother had rubbed it.\n\n\"Hey, Mom, guess what? Guess who we just met on the train?\"\n\nHarry leaned back quickly so they couldn't see him looking.\n\n\"You know that black-haired boy who was near us in the station? Know who\nhe is?\"\n\n\"Who?\"\n\n\"Harry Potter!\"\n\nHarry heard the little girl's voice.\n\n\"Oh, Mom, can I go on the train and see him, Mom, eh please....\"\n\n\"You've already seen him, Ginny, and the poor boy isn't something you\ngoggle at in a zoo. Is he really, Fred? How do you know?\"\n\n\"Asked him. Saw his scar. It's really there - like lightning.\"\n\n\"Poor dear - no wonder he was alone, I wondered. He was ever so polite\nwhen he asked how to get onto the platform.\"\n\n\"Never mind that, do you think he remembers what You-Know-Who looks\nlike?\"\n\nTheir mother suddenly became very stern.\n\n\"I forbid you to ask him, Fred. No, don't you dare. As though he needs\nreminding of that on his first day at school.\"\n\n\"All right, keep your hair on.\"\n\nA whistle sounded.\n\n\"Hurry up!\" their mother said, and the three boys clambered onto the\ntrain. They leaned out of the window for her to kiss them good-bye, and\ntheir younger sister began to cry.\n\n\"Don't, Ginny, we'll send you loads of owls.\"\n\n\"We'll send you a Hogwarts toilet seat.\"\n\n\"George!\"\n\n\"Only joking, Mom.\"\n\nThe train began to move. Harry saw the boys' mother waving and their\nsister, half laughing, half crying, running to keep up with the train\nuntil it gathered too much speed, then she fell back and waved.\n\nHarry watched the girl and her mother disappear as the train rounded the\ncorner. Houses flashed past the window. Harry felt a great leap of\nexcitement. He didn't know what he was going to but it had to be better\nthan what he was leaving behind.\n\nThe door of the compartment slid open and the youngest redheaded boy\ncame in.\n\n\"Anyone sitting there?\" he asked, pointing at the seat opposite Harry.\n\"Everywhere else is full.\"\n\nHarry shook his head and the boy sat down. He glanced at Harry and then\nlooked quickly out of the window, pretending he hadn't looked. Harry saw\nhe still had a black mark on his nose.\n\n\"Hey, Ron.\"\n\nThe twins were back.\n\n\"Listen, we're going down the middle of the train -- Lee Jordan's got a\ngiant tarantula down there.\"\n\n\"Right,\" mumbled Ron.\n\n\"Harry,\" said the other twin, \"did we introduce ourselves? Fred and\nGeorge Weasley. And this is Ron, our brother. See you later, then.\n\n\"Bye,\" said Harry and Ron. The twins slid the compartment door shut\nbehind them.\n\n\"Are you really Harry Potter?\" Ron blurted out.\n\nHarry nodded.\n\n\"Oh -well, I thought it might be one of Fred and George's jokes,\" said\nRon. \"And have you really got -- you know...\"\n\nHe pointed at Harry's forehead.\n\nHarry pulled back his bangs to show the lightning scar. Ron stared.\n\n\"So that's where You-Know-Who\n\n\"Yes,\" said Harry, \"but I can't remember it.\"\n\n\"Nothing?\" said Ron eagerly.\n\n\"Well -- I remember a lot of green light, but nothing else.\"\n\n\"Wow,\" said Ron. He sat and stared at Harry for a few moments, then, as\nthough he had suddenly realized what he was doing, he looked quickly out\nof the window again.\n\n\"Are all your family wizards?\" asked Harry, who found Ron just as\ninteresting as Ron found him.\n\n\"Er -- Yes, I think so,\" said Ron. \"I think Mom's got a second cousin\nwho's an accountant, but we never talk about him.\"\n\n\"So you must know loads of magic already.\"\n\nThe Weasleys were clearly one of those old wizarding families the pale\nboy in Diagon Alley had talked about.\n\n\"I heard you went to live with Muggles,\" said Ron. \"What are they like?\"\n\n\"Horrible -well, not all of them. My aunt and uncle and cousin are,\nthough. Wish I'd had three wizard brothers.\"\n\n\"Five,\" said Ron. For some reason, he was looking gloomy. \"I'm the sixth\nin our family to go to Hogwarts. You could say I've got a lot to live up\nto. Bill and Charlie have already left -- Bill was head boy and Charlie\nwas captain of Quidd"
    }
}
{
    "type": "error",
    "data": "Entity Extraction Error",
    "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 122, in __call__\n    result = await self._process_document(text, prompt_variables)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 161, in _process_document\n    response = await self._llm(\n               ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\json_parsing_llm.py\", line 34, in __call__\n    result = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_token_replacing_llm.py\", line 37, in __call__\n    return await self._delegate(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_history_tracking_llm.py\", line 33, in __call__\n    output = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\caching_llm.py\", line 96, in __call__\n    result = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 177, in __call__\n    result, start = await execute_with_retry()\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 159, in execute_with_retry\n    async for attempt in retryer:\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 166, in __anext__\n    do = await self.iter(retry_state=self._retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 153, in iter\n    result = await action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\_utils.py\", line 99, in inner\n    return call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\__init__.py\", line 418, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\__init__.py\", line 185, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\concurrent\\futures\\_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\concurrent\\futures\\_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 165, in execute_with_retry\n    return await do_attempt(), start\n           ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 151, in do_attempt\n    await sleep_for(sleep_time)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 147, in do_attempt\n    return await self._delegate(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 50, in __call__\n    return await self._invoke(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 54, in _invoke\n    output = await self._execute_llm(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_chat_llm.py\", line 53, in _execute_llm\n    completion = await self.client.chat.completions.create(\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\resources\\chat\\completions.py\", line 1661, in create\n    return await self._post(\n           ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1839, in post\n    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1533, in request\n    return await self._request(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1634, in _request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 194484, Requested 7538. Please try again in 606ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}\n",
    "source": "Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 194484, Requested 7538. Please try again in 606ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}",
    "details": {
        "doc_index": 0,
        "text": ".\"\n\n\"Kept outta trouble, though, that's somethin',\" said Hagrid, raising his\nbinoculars and peering skyward at the speck that was Harry.\n\nWay up above them, Harry was gliding over the game, squinting about for\nsome sign of the Snitch. This was part of his and Wood's game plan.\n\n\"Keep out of the way until you catch sight of the Snitch,\" Wood had\nsaid. \"We don't want you attacked before you have to be.\"\n\nWhen Angelina had scored, Harry had done a couple of loop-the-loops to\nlet off his feelings. Now he was back to staring around for the Snitch.\nOnce he caught sight of a flash of gold, but it was just a reflection\nfrom one of the Weasleys' wristwatches, and once a Bludger decided to\ncome pelting his way, more like a cannonball than anything, but Harry\ndodged it and Fred Weasley came chasing after it.\n\n\"All right there, Harry?\" he had time to yell, as he beat the Bludger\nfuriously toward Marcus Flint.\n\n\"Slytherin in possession,\" Lee Jordan was saying, \"Chaser Pucey ducks\ntwo Bludgers, two Weasleys, and Chaser Bell, and speeds toward the --\nwait a moment -- was that the Snitch?\"\n\nA murmur ran through the crowd as Adrian Pucey dropped the Quaffle, too\nbusy looking over his shoulder at the flash of gold that had passed his\nleft ear.\n\nHarry saw it. In a great rush of excitement he dived downward after the\nstreak of gold. Slytherin Seeker Terence Higgs had seen it, too. Neck\nand neck they hurtled toward the Snitch -all the Chasers seemed to have\nforgotten what they were supposed to be doing as they hung in midair to\nwatch.\n\nHarry was faster than Higgs -- he could see the little round ball, wings\nfluttering, darting up ahead - - he put on an extra spurt of speed --\n\nWHAM! A roar of rage echoed from the Gryffindors below -- Marcus Flint\nhad blocked Harry on purpose, and Harry's broom spun off course, Harry\nholding on for dear life.\n\n\"Foul!\" screamed the Gryffindors.\n\nMadam Hooch spoke angrily to Flint and then ordered a free shot at the\ngoal posts for Gryffindor. But in all the confusion, of course, the\nGolden Snitch had disappeared from sight again.\n\nDown in the stands, Dean Thomas was yelling, \"Send him off, ref! Red\ncard!\"\n\n\"What are you talking about, Dean?\" said Ron.\n\n\"Red card!\" said Dean furiously. \"In soccer you get shown the red card\nand you're out of the game!\"\n\n\"But this isn't soccer, Dean,\" Ron reminded him.\n\nHagrid, however, was on Dean's side.\n\n\"They oughta change the rules. Flint coulda knocked Harry outta the\nair.\"\n\nLee Jordan was finding it difficult not to take sides.\n\n\"So -- after that obvious and disgusting bit of cheating\n\n\"Jordan!\" growled Professor McGonagall.\n\n\"I mean, after that open and revolting foul\n\n'Jordan, I'm warning you --\"\n\n\"All right, all right. Flint nearly kills the Gryffindor Seeker, which\ncould happen to anyone, I'm sure, so a penalty to Gryffindor, taken by\nSpinner, who puts it away, no trouble, and we continue play, Gryffindor\nstill in possession.\"\n\nIt was as Harry dodged another Bludger, which went spinning dangerously\npast his head, that it happened. His broom gave a sudden, frightening\nlurch. For a split second, he thought he was going to fall. He gripped\nthe broom tightly with both his hands and knees. He'd never felt\nanything like that.\n\nIt happened again. It was as though the broom was trying to buck him\noff. But Nimbus Two Thousands did not suddenly decide to buck their\nriders off. Harry tried to turn back toward the Gryffindor goal- posts\n-- he had half a mind to ask Wood to call time-out -- and then he\nrealized that his broom was completely out of his control. He couldn't\nturn it. He couldn't direct it at all. It was zigzagging through the\nair, and every now and then making violent swishing movements that\nalmost unseated him.\n\nLee was still commentating.\n\n\"Slytherin in possession -- Flint with the Quaffle -- passes Spinnet --\npasses Bell -- hit hard in the face by a Bludger, hope it broke his nose\n-- only joking, Professor -- Slytherins score -- A no...\n\nThe Slytherins were cheering. No one seemed to have noticed that Harry's\nbroom was behaving strangely. It was carrying- him slowly higher, away\nfrom the game, jerking and twitching as it went.\n\n\"Dunno what Harry thinks he's doing,\" Hagrid mumbled. He stared through\nhis binoculars. \"If I didn' know better, I'd say he'd lost control of\nhis broom... but he can't have....\"\n\nSuddenly, people were pointing up at Harry all over the stands. His\nbroom had started to roll over and over, with him only just managing to\nhold on. Then the whole crowd gasped. Harry's broom had given a wild\njerk and Harry swung off it. He was now dangling from it, holding on\nwith only one hand.\n\n\"Did something happen to it when Flint blocked him?\" Seamus whispered.\n\n\"Can't have,\" H"
    }
}
{
    "type": "error",
    "data": "Entity Extraction Error",
    "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 122, in __call__\n    result = await self._process_document(text, prompt_variables)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 161, in _process_document\n    response = await self._llm(\n               ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\json_parsing_llm.py\", line 34, in __call__\n    result = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_token_replacing_llm.py\", line 37, in __call__\n    return await self._delegate(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_history_tracking_llm.py\", line 33, in __call__\n    output = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\caching_llm.py\", line 96, in __call__\n    result = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 177, in __call__\n    result, start = await execute_with_retry()\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 159, in execute_with_retry\n    async for attempt in retryer:\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 166, in __anext__\n    do = await self.iter(retry_state=self._retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 153, in iter\n    result = await action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\_utils.py\", line 99, in inner\n    return call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\__init__.py\", line 418, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\__init__.py\", line 185, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\concurrent\\futures\\_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\concurrent\\futures\\_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 165, in execute_with_retry\n    return await do_attempt(), start\n           ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 151, in do_attempt\n    await sleep_for(sleep_time)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 147, in do_attempt\n    return await self._delegate(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 50, in __call__\n    return await self._invoke(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 54, in _invoke\n    output = await self._execute_llm(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_chat_llm.py\", line 53, in _execute_llm\n    completion = await self.client.chat.completions.create(\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\resources\\chat\\completions.py\", line 1661, in create\n    return await self._post(\n           ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1839, in post\n    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1533, in request\n    return await self._request(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1634, in _request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 195460, Requested 7653. Please try again in 933ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}\n",
    "source": "Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 195460, Requested 7653. Please try again in 933ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}",
    "details": {
        "doc_index": 0,
        "text": "saw\nhim!\"\n\n\"I'm tellin' yeh, yer wrong!\" said Hagrid hotly. \"I don' know why\nHarry's broom acted like that, but Snape wouldn' try an' kill a student!\nNow, listen to me, all three of yeh -- yer meddlin' in things that don'\nconcern yeh. It's dangerous. You forget that dog, an' you forget what\nit's guardin', that's between Professor Dumbledore an' Nicolas Flamel\n--\"\n\n\"Aha!\" said Harry, \"so there's someone called Nicolas Flamel involved,\nis there?\"\n\nHagrid looked furious with himself.\n\n\nCHAPTER TWELVE\n\nTHE MIRROR OF ERISED\n\nChristmas was coming. One morning in mid-December, Hogwarts woke to find\nitself covered in several feet of snow. The lake froze solid and the\nWeasley twins were punished for bewitching several snowballs so that\nthey followed Quirrell around, bouncing off the back of his turban. The\nfew owls that managed to battle their way through the stormy sky to\ndeliver mail had to be nursed back to health by Hagrid before they could\nfly off again.\n\nNo one could wait for the holidays to start. While the Gryffindor common\nroom and the Great Hall had roaring fires, the drafty corridors had\nbecome icy and a bitter wind rattled the windows in the classrooms.\nWorst of all were Professor Snape's classes down in the dungeons, where\ntheir breath rose in a mist before them and they kept as close as\npossible to their hot cauldrons.\n\n\"I do feel so sorry,\" said Draco Malfoy, one Potions class, \"for all\nthose people who have to stay at Hogwarts for Christmas because they're\nnot wanted at home.\"\n\nHe was looking over at Harry as he spoke. Crabbe and Goyle chuckled.\nHarry, who was measuring out powdered spine of lionfish, ignored them.\nMalfoy had been even more unpleasant than usual since the Quidditch\nmatch. Disgusted that the Slytherins had lost, he had tried to get\neveryone laughing at how a wide-mouthed tree frog would be replacing\nHarry as Seeker next. Then he'd realized that nobody found this funny,\nbecause they were all so impressed at the way Harry had managed to stay\non his bucking broomstick. So Malfoy, jealous and angry, had gone back\nto taunting Harry about having no proper family.\n\nIt was true that Harry wasn't going back to Privet Drive for Christmas.\nProfessor McGonagall had come around the week before, making a list of\nstudents who would be staying for the holidays, and Harry had signed up\nat once. He didn't feel sorry for himself at all; this would probably be\nthe best Christmas he'd ever had. Ron and his brothers were staying,\ntoo, because Mr. and Mrs. Weasley were going to Romania to visit\nCharlie.\n\nWhen they left the dungeons at the end of Potions, they found a large\nfir tree blocking the corridor ahead. Two enormous feet sticking out at\nthe bottom and a loud puffing sound told them that Hagrid was behind it.\n\n\"Hi, Hagrid, want any help?\" Ron asked, sticking his head through the\nbranches.\n\n\"Nah, I'm all right, thanks, Ron.\"\n\n\"Would you mind moving out of the way?\" came Malfoys cold drawl from\nbehind them. \"Are you trying to earn some extra money, Weasley? Hoping\nto be gamekeeper yourself when you leave Hogwarts, I suppose -- that hut\nof Hagrid's must seem like a palace compared to what your family's used\nto.\"\n\nRon dived at Malfoy just as Snape came up the stairs.\n\n\"WEASLEY!\"\n\nRon let go of the front of Malfoy's robes.\n\n\"He was provoked, Professor Snape,\" said Hagrid, sticking his huge hairy\nface out from behind the tree. \"Malfoy was insultin' his family.\"\n\n\"Be that as it may, fighting is against Hogwarts rules, Hagrid,\" said\nSnape silkily. \"Five points from Gryffindor, Weasley, and be grateful it\nisn't more. Move along, all of you.\"\n\nMalfoy, Crabbe, and Goyle pushed roughly past the tree, scattering\nneedles everywhere and smirking.\n\n\"I'll get him,\" said Ron, grinding his teeth at Malfoy's back, \"one of\nthese days, I'll get him --\"\n\n\"I hate them both,\" said Harry, \"Malfoy and Snape.\"\n\n\"Come on, cheer up, it's nearly Christmas,\" said Hagrid. \"Tell yeh what,\ncome with me an' see the Great Hall, looks a treat.\"\n\nSo the three of them followed Hagrid and his tree off to -the Great\nHall, where Professor McGonagall and Professor Flitwick were busy with\nthe Christmas decorations.\n\n\"Ah, Hagrid, the last tree -- put it in the far corner, would you?\"\n\nThe hall looked spectacular. Festoons of holly and mistletoe hung all\naround the walls, and no less than twelve towering Christmas trees stood\naround the room, some sparkling with tiny icicles, some glittering with\nhundreds of candles.\n\n\"How many days you got left until yer holidays?\" Hagrid asked.\n\n\"Just one,\" said Hermione. \"And that reminds me -Harry, Ron, we've got\nhalf an hour before lunch, we should be in the library.\"\n\n\"Oh yeah, you're right,\" said Ron, tearing his eyes away from Professor\nFlitwick, who had golden bubbles blossoming out of his wand and was\ntrailing them over the branches of the new tree.\n\n\"The library?\" said H"
    }
}
{
    "type": "error",
    "data": "Entity Extraction Error",
    "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 122, in __call__\n    result = await self._process_document(text, prompt_variables)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 161, in _process_document\n    response = await self._llm(\n               ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\json_parsing_llm.py\", line 34, in __call__\n    result = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_token_replacing_llm.py\", line 37, in __call__\n    return await self._delegate(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_history_tracking_llm.py\", line 33, in __call__\n    output = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\caching_llm.py\", line 96, in __call__\n    result = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 177, in __call__\n    result, start = await execute_with_retry()\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 159, in execute_with_retry\n    async for attempt in retryer:\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 166, in __anext__\n    do = await self.iter(retry_state=self._retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 153, in iter\n    result = await action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\_utils.py\", line 99, in inner\n    return call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\__init__.py\", line 418, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\__init__.py\", line 185, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\concurrent\\futures\\_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\concurrent\\futures\\_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 165, in execute_with_retry\n    return await do_attempt(), start\n           ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 151, in do_attempt\n    await sleep_for(sleep_time)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 147, in do_attempt\n    return await self._delegate(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 50, in __call__\n    return await self._invoke(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 54, in _invoke\n    output = await self._execute_llm(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_chat_llm.py\", line 53, in _execute_llm\n    completion = await self.client.chat.completions.create(\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\resources\\chat\\completions.py\", line 1661, in create\n    return await self._post(\n           ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1839, in post\n    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1533, in request\n    return await self._request(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1634, in _request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 195243, Requested 7319. Please try again in 768ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}\n",
    "source": "Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 195243, Requested 7319. Please try again in 768ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}",
    "details": {
        "doc_index": 0,
        "text": "way along the rows of books. The lamp looked as if it was floating along\nin midair, and even though Harry could feel his arm supporting it, the\nsight gave him the creeps.\n\nThe Restricted Section was right at the back of the library. Step ping\ncarefully over the rope that separated these books from the rest of the\nlibrary, he held up his lamp to read the titles.\n\nThey didn't tell him much. Their peeling, faded gold letters spelled\nwords in languages Harry couldn't understand. Some had no title at all.\nOne book had a dark stain on it that looked horribly like blood. The\nhairs on the back of Harry's neck prickled. Maybe he was imagining it,\nmaybe not, but he thought a faint whispering was coming from the books,\nas though they knew someone was there who shouldn't be.\n\nHe had to start somewhere. Setting the lamp down carefully on the floor,\nhe looked along the bottom shelf for an interestinglooking book. A large\nblack and silver volume caught his eye. He pulled it out with\ndifficulty, because it was very heavy, and, balancing it on his knee,\nlet it fall open.\n\nA piercing, bloodcurdling shriek split the silence -- the book was\nscreaming! Harry snapped it shut, but the shriek went on and on, one\nhigh, unbroken, earsplitting note. He stumbled backward and knocked over\nhis lamp, which went out at once. Panicking, he heard footsteps coming\ndown the corridor outside -- stuffing the shrieking book back on the\nshelf, he ran for it. He passed Filch in the doorway; Filch's pale, wild\neyes looked straight through him, and Harry slipped under Filch's\noutstretched arm and streaked off up the corridor, the book's shrieks\nstill ringing in his ears.\n\nHe came to a sudden halt in front of a tall suit of armor. He had been\nso busy getting away from the library, he hadn't paid attention to where\nhe was going. Perhaps because it was dark, he didn't recognize where he\nwas at all. There was a suit of armor near the kitchens, he knew, but he\nmust be five floors above there.\n\n\"You asked me to come directly to you, Professor, if anyone was\nwandering around at night, and somebody's been in the library Restricted\nSection.\"\n\nHarry felt the blood drain out of his face. Wherever he was, Filch must\nknow a shortcut, because his soft, greasy voice was getting nearer, and\nto his horror, it was Snape who replied, \"The Restricted Section? Well,\nthey can't be far, we'll catch them.\"\n\nHarry stood rooted to the spot as Filch and Snape came around the corner\nahead. They couldn't see him, of course, but it was a narrow corridor\nand if they came much nearer they'd knock right into him -- the cloak\ndidn't stop him from being solid.\n\nHe backed away as quietly as he could. A door stood ajar to his left. It\nwas his only hope. He squeezed through it, holding his breath, trying\nnot to move it, and to his relief he managed to get inside the room\nwithout their noticing anything. They walked straight past, and Harry\nleaned against the wall, breathing deeply, listening to their footsteps\ndying away. That had been close, very close. It was a few seconds before\nhe noticed anything about the room he had hidden in.\n\nIt looked like an unused classroom. The dark shapes of desks and chairs\nwere piled against the walls, and there was an upturned wastepaper\nbasket -- but propped against the wall facing him was something that\ndidn't look as if it belonged there, something that looked as if someone\nhad just put it there to keep it out of the way.\n\nIt was a magnificent mirror, as high as the ceiling, with an ornate gold\nframe, standing on two clawed feet. There was an inscription carved\naround the top: Erised stra ehru oyt ube cafru oyt on wohsi. His panic\nfading now that there was no sound of Filch and Snape, Harry moved\nnearer to the mirror, wanting to look at himself but see no reflection\nagain. He stepped in front of it.\n\nHe had to clap his hands to his mouth to stop himself from screaming. He\nwhirled around. His heart was pounding far more furiously than when the\nbook had screamed -- for he had seen not only himself in the mirror, but\na whole crowd of people standing right behind him.\n\nBut the room was empty. Breathing very fast, he turned slowly back to\nthe mirror.\n\nThere he was, reflected in it, white and scared-looking, and there,\nreflected behind him, were at least ten others. Harry looked over his\nshoulder -- but still, no one was there. Or were they all invisible,\ntoo? Was he in fact in a room full of invisible people and this mirror's\ntrick was that it reflected them, invisible or not?\n\nHe looked in the mirror again. A woman standing right behind his\nreflection was smiling at him and waving. He reached out a hand and felt\nthe air behind him. If she was really there, he'd touch her, their\nreflections were so close together, but he felt only air -- she and the\nothers existed only in the mirror.\n\nShe was a very pretty woman. She had dark red hair and her eyes -- her\neyes are just like mine, Harry thought, edging a little closer to the\nglass. Bright green -- exactly the same shape, but then he noticed that\nshe was crying; smiling, but crying at the same"
    }
}
{
    "type": "error",
    "data": "Entity Extraction Error",
    "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 122, in __call__\n    result = await self._process_document(text, prompt_variables)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 161, in _process_document\n    response = await self._llm(\n               ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\json_parsing_llm.py\", line 34, in __call__\n    result = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_token_replacing_llm.py\", line 37, in __call__\n    return await self._delegate(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_history_tracking_llm.py\", line 33, in __call__\n    output = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\caching_llm.py\", line 96, in __call__\n    result = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 177, in __call__\n    result, start = await execute_with_retry()\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 159, in execute_with_retry\n    async for attempt in retryer:\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 166, in __anext__\n    do = await self.iter(retry_state=self._retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 153, in iter\n    result = await action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\_utils.py\", line 99, in inner\n    return call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\__init__.py\", line 418, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\__init__.py\", line 185, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\concurrent\\futures\\_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\concurrent\\futures\\_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 165, in execute_with_retry\n    return await do_attempt(), start\n           ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 151, in do_attempt\n    await sleep_for(sleep_time)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 147, in do_attempt\n    return await self._delegate(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 50, in __call__\n    return await self._invoke(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 54, in _invoke\n    output = await self._execute_llm(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_chat_llm.py\", line 53, in _execute_llm\n    completion = await self.client.chat.completions.create(\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\resources\\chat\\completions.py\", line 1661, in create\n    return await self._post(\n           ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1839, in post\n    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1533, in request\n    return await self._request(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1634, in _request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 196388, Requested 7636. Please try again in 1.207s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}\n",
    "source": "Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 196388, Requested 7636. Please try again in 1.207s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}",
    "details": {
        "doc_index": 0,
        "text": "'d have gotten through all his homework without her, what\nwith all the last-minute Quidditch practice Wood was making them do. She\nhad also tent him Quidditch Through the Ages, which turned out to be a\nvery interesting read.\n\nHarry learned that there were seven hundred ways of committing a\nQuidditch foul and that all of them had happened during a World Cup\nmatch in 1473; that Seekers were usually the smallest and fastest\nplayers, and that most serious Quidditch accidents seemed to happen to\nthem; that although people rarely died playing Quidditch, referees had\nbeen known to vanish and turn up months later in the Sahara Desert.\n\nHermione had become a bit more relaxed about breaking rules since Harry\nand Ron had saved her from the mountain troll, and she was much nicer\nfor it. The day before Harry's first Quidditch match the three of them\nwere out in the freezing courtyard during break, and she had conjured\nthem up a bright blue fire that could be carried around in a jam jar.\nThey were standing with their backs to it, getting warm, when Snape\ncrossed the yard. Harry noticed at once that Snape was limping. Harry,\nRon, and Hermione moved closer together to block the fire from view;\nthey were sure it wouldn't be allowed. Unfortunately, something about\ntheir guilty faces caught Snape's eye. He limped over. He hadn't seen\nthe fire, but he seemed to be looking for a reason to tell them off\nanyway.\n\n\"What's that you've got there, Potter?\"\n\nIt was Quidditch Through the Ages. Harry showed him.\n\n\"Library books are not to be taken outside the school,\" said Snape.\n\"Give it to me. Five points from Gryffindor.\"\n\n\"He's just made that rule up,\" Harry muttered angrily as Snape limped\naway. \"Wonder what's wrong with his leg?\"\n\n\"Dunno, but I hope it's really hurting him,\" said Ron bitterly.\n\nThe Gryffindor common room was very noisy that evening. Harry, Ron, and\nHermione sat together next to a window. Hermione was checking Harry and\nRon's Charms homework for them. She would never let them copy (\"How will\nyou learn?\"), but by asking her to read it through, they got the right\nanswers anyway.\n\nHarry felt restless. He wanted Quidditch Through the Ages back, to take\nhis mind off his nerves about tomorrow. Why should he be afraid of\nSnape? Getting up, he told Ron and Hermione he was going to ask Snape if\nhe could have it.\n\n\"Better you than me,\" they said together, but Harry had an idea that\nSnape wouldn't refuse if there were other teachers listening.\n\nHe made his way down to the staffroom and knocked. There was no answer.\nHe knocked again. Nothing.\n\nPerhaps Snape had left the book in there? It was worth a try. He pushed\nthe door ajar and peered inside -- and a horrible scene met his eyes.\n\nSnape and Filch were inside, alone. Snape was holding his robes above\nhis knees. One of his legs was bloody and mangled. Filch was handing\nSnape bandages.\n\n\"Blasted thing*,\" Snape was saying. \"How are you supposed to keep your\neyes on all three heads at once?\"\n\nHarry tried to shut the door quietly, but --\n\n\"POTTER!\"\n\nSnape's face was twisted with fury as he dropped his robes quickly to\nhide his leg. Harry gulped.\n\n\"I just wondered if I could have my book back.\"\n\n\"GET OUT! OUT!\"\n\nHarry left, before Snape could take any more points from Gryffindor. He\nsprinted back upstairs.\n\n\"Did you get it?\" Ron asked as Harry joined them. \"What's the matter?\"\n\nIn a low whisper, Harry told them what he'd seen.\n\n\"You know what this means?\" he finished breathlessly. \"He tried to get\npast that three-headed dog at Halloween! That's where he was going when\nwe saw him -- he's after whatever it's guarding! And Id bet my\nbroomstick he let that troll in, to make a diversion!\"\n\nHermione's eyes were wide.\n\n\"No -- he wouldn't, she said. \"I know he's not very nice, but he\nwouldn't try and steal something Dumbledore was keeping safe.\"\n\n\"Honestly, Hermione, you think all teachers are saints or something,\"\nsnapped Ron. \"I'm with Harry. I wouldn't put anything past Snape. But\nwhat's he after? What's that dog guarding?\"\n\nHarry went to bed with his head buzzing with the same question. Neville\nwas snoring loudly, but Harry couldn't sleep. He tried to empty his mind\n-- he needed to sleep, he had to, he had his first Quidditch match in a\nfew hours -- but the expression on Snape's face when Harry had seen his\nleg wasn't easy to forget.\n\nThe next morning dawned very bright and cold. The Great Hall was full of\nthe delicious smell of fried sausages and the cheer ful chatter of\neveryone looking forward to a good Quidditch match.\n\n\"You've got to eat some breakfast.\"\n\n\"I don't want anything.\"\n\n\"Just a bit of toast,\" wheedled Hermione.\n\n\"I'm not hungry.\"\n\nHarry felt terrible. In an hour's time he'd be walking onto the field.\n\n\"Harry, you need your strength,\" said Seamus Finnigan. \"Seekers are\nalways the ones who get clobbered by the other team.\"\n\n\"Thanks, Seamus,\" said Harry, watching Seamus pile ketchup on his\nsausages.\n\nBy eleven o'clock the whole school seemed to be out in the stands around\nthe Quidditch pitch."
    }
}
{
    "type": "error",
    "data": "Entity Extraction Error",
    "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 122, in __call__\n    result = await self._process_document(text, prompt_variables)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 161, in _process_document\n    response = await self._llm(\n               ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\json_parsing_llm.py\", line 34, in __call__\n    result = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_token_replacing_llm.py\", line 37, in __call__\n    return await self._delegate(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_history_tracking_llm.py\", line 33, in __call__\n    output = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\caching_llm.py\", line 96, in __call__\n    result = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 177, in __call__\n    result, start = await execute_with_retry()\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 159, in execute_with_retry\n    async for attempt in retryer:\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 166, in __anext__\n    do = await self.iter(retry_state=self._retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 153, in iter\n    result = await action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\_utils.py\", line 99, in inner\n    return call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\__init__.py\", line 418, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\__init__.py\", line 185, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\concurrent\\futures\\_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\concurrent\\futures\\_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 165, in execute_with_retry\n    return await do_attempt(), start\n           ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 151, in do_attempt\n    await sleep_for(sleep_time)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 147, in do_attempt\n    return await self._delegate(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 50, in __call__\n    return await self._invoke(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 54, in _invoke\n    output = await self._execute_llm(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_chat_llm.py\", line 53, in _execute_llm\n    completion = await self.client.chat.completions.create(\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\resources\\chat\\completions.py\", line 1661, in create\n    return await self._post(\n           ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1839, in post\n    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1533, in request\n    return await self._request(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1634, in _request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 197988, Requested 7297. Please try again in 1.585s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}\n",
    "source": "Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 197988, Requested 7297. Please try again in 1.585s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}",
    "details": {
        "doc_index": 0,
        "text": "you know? They loathed each other. But he never\nwanted you dead.\"\n\n\"But I heard you a few days ago, sobbing -- I thought Snape was\nthreatening you....\"\n\nFor the first time, a spasm of fear flitted across Quirrell's face.\n\n\"Sometimes,\" he said, \"I find it hard to follow my master's instructions\n-- he is a great wizard and I am weak --\"\n\n\"You mean he was there in the classroom with you?\" Harry gasped.\n\n\"He is with me wherever I go,\" said Quirrell quietly. \"I met him when I\ntraveled around the world. A foolish young man I was then, full of\nridiculous ideas about good and evil. Lord Voldemort showed me how wrong\nI was. There is no good and evil, there is only power, and those too\nweak to seek it.... Since then, I have served him faithfully, although I\nhave let him down many times. He has had to be very hard on me.\"\nQuirrell shivered suddenly. \"He does not forgive mistakes easily. When I\nfailed to steal the stone from Gringotts, he was most displeased. He\npunished me... decided he would have to keep a closer watch on me....\"\n\nQuirrell's voice trailed away. Harry was remembering his trip to Diagon\nAlley -how could he have been so stupid? He'd seen Quirrell there that\nvery day, shaken hands with him in the Leaky Cauldron.\n\nQuirrell cursed under his breath.\n\n\"I don't understand... is the Stone inside the mirror? Should I break\nit?\"\n\nHarry's mind was racing.\n\nWhat I want more than anything else in the world at the moment, he\nthought, is to find the Stone before Quirrell does. So if I look in the\nmirror, I should see myseff finding it -- which means I'll see where\nit's hidden! But how can I look without Quirrell realizing what I'm up\nto?\n\nHe tried to edge to the left, to get in front of the glass without\nQuirrell noticing, but the ropes around his ankles were too tight: he\ntripped and fell over. Quirrell ignored him. He was still talking to\nhimself. \"What does this mirror do? How does it work? Help me, Master!\"\n\nAnd to Harry's horror, a voice answered, and the voice seemed to come\nfrom Quirrell himself\n\n\"Use the boy... Use the boy...\"\n\nQuirrell rounded on Harry.\n\n\"Yes -- Potter -- come here.\"\n\nHe clapped his hands once, and the ropes binding Harry fell off. Harry\ngot slowly to his feet.\n\n\"Come here,\" Quirrell repeated. \"Look in the mirror and tell me what you\nsee.\"\n\nHarry walked toward him.\n\nI must lie, he thought desperately. I must look and lie about what I\nsee, that's all.\n\nQuirrell moved close behind him. Harry breathed in the funny smell that\nseemed to come from Quirrell's turban. He closed his eyes, stepped in\nfront of the mirror, and opened them again.\n\nHe saw his reflection, pale and scared-looking at first. But a moment\nlater, the reflection smiled at him. It put its hand into its pocket and\npulled out a blood-red stone. It winked and put the Stone back in its\npocket -- and as it did so, Harry felt something heavy drop into his\nreal pocket. Somehow -- incredibly -- he'd gotten the Stone.\n\n\"Well?\" said Quirrell impatiently. \"What do you see?\"\n\nHarry screwed up his courage.\n\n\"I see myself shaking hands with Dumbledore,\" he invented. \"I -- I've\nwon the house cup for Gryffindor.\"\n\nQuirrell cursed again.\n\n\"Get out of the way,\" he said. As Harry moved aside, he felt the\nSorcerer's Stone against his leg. Dare he make a break for it?\n\nBut he hadn't walked five paces before a high voice spoke, though\nQuirrell wasn't moving his lips.\n\n\"He lies... He lies...\"\n\n\"Potter, come back here!\" Quirrell shouted. \"Tell me the truth! What did\nyou just see?\"\n\nThe high voice spoke again.\n\n\"Let me speak to him... face-to-face...\"\n\n\"Master, you are not strong enough!\"\n\n\"I have strength enough... for this....\"\n\nHarry felt as if Devil's Snare was rooting him to the spot. He couldn't\nmove a muscle. Petrified, he watched as Quirrell reached up and began to\nunwrap his turban. What was going on? The turban fell away. Quirrell's\nhead looked strangely small without it. Then he turned slowly on the\nspot.\n\nHarry would have screamed, but he couldn't make a sound. Where there\nshould have been a back to Quirrell's head, there was a face, the most\nterrible face Harry had ever seen. It was chalk white with glaring red\neyes and slits for nostrils, like a snake.\n\n\"Harry Potter...\" it whispered.\n\nHarry tried to take a step backward but his legs wouldn't move.\n\n\"See what I have become?\" the face said. \"Mere shadow and vapor ... I\nhave form only when I can share another's body... but there have always\nbeen those willing to let me into their hearts and minds.... Unicorn\nblood has strengthened me, these past weeks... you saw faithful Quirrell\ndrinking it for me in the forest... and once I have the Elixir of Life,\nI will be able to create a body of my own.... Now... why don't you give\nme that Stone in your pocket?\"\n\nSo he knew. The"
    }
}
{
    "type": "error",
    "data": "Entity Extraction Error",
    "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 122, in __call__\n    result = await self._process_document(text, prompt_variables)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 161, in _process_document\n    response = await self._llm(\n               ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\json_parsing_llm.py\", line 34, in __call__\n    result = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_token_replacing_llm.py\", line 37, in __call__\n    return await self._delegate(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_history_tracking_llm.py\", line 33, in __call__\n    output = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\caching_llm.py\", line 96, in __call__\n    result = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 177, in __call__\n    result, start = await execute_with_retry()\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 159, in execute_with_retry\n    async for attempt in retryer:\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 166, in __anext__\n    do = await self.iter(retry_state=self._retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 153, in iter\n    result = await action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\_utils.py\", line 99, in inner\n    return call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\__init__.py\", line 418, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\tenacity\\__init__.py\", line 185, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\concurrent\\futures\\_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\concurrent\\futures\\_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 165, in execute_with_retry\n    return await do_attempt(), start\n           ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 151, in do_attempt\n    await sleep_for(sleep_time)\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 147, in do_attempt\n    return await self._delegate(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 50, in __call__\n    return await self._invoke(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 54, in _invoke\n    output = await self._execute_llm(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_chat_llm.py\", line 53, in _execute_llm\n    completion = await self.client.chat.completions.create(\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\resources\\chat\\completions.py\", line 1661, in create\n    return await self._post(\n           ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1839, in post\n    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1533, in request\n    return await self._request(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\andyp\\anaconda3\\envs\\graphrag-local\\Lib\\site-packages\\openai\\_base_client.py\", line 1634, in _request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 194675, Requested 7610. Please try again in 685ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}\n",
    "source": "Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-WOx4zVSIr5TxCLinW96Lvbcd on tokens per min (TPM): Limit 200000, Used 194675, Requested 7610. Please try again in 685ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}",
    "details": {
        "doc_index": 0,
        "text": "happened to leave it in my possession, and I thought\nyou might like it.\" Dumbledore's eyes twinkled. \"Useful things... your\nfather used it mainly for sneaking off to the kitchens to steal food\nwhen he was here.\"\n\n\"And there's something else...\"\n\n\"Fire away.\"\n\n\"Quirrell said Snape --\"\n\n\"Professor Snape, Harry.\" \"Yes, him -- Quirrell said he hates me because\nhe hated my father. Is that true?\"\n\n\"Well, they did rather detest each other. Not unlike yourself and Mr.\nMalfoy. And then, your father did something Snape could never forgive.\"\n\n\"What?\"\n\n\"He saved his life.\"\n\n\"What?\"\n\n\"Yes...\" said Dumbledore dreamily. \"Funny, the way people's minds work,\nisn't it? Professor Snape couldn't bear being in your father's debt....\nI do believe he worked so hard to protect you this year because he felt\nthat would make him and your father even. Then he could go back to\nhating your father's memory in peace....\"\n\nHarry tried to understand this but it made his head pound, so he\nstopped.\n\n\"And sir, there's one more thing...\"\n\n\"Just the one?\"\n\n\"How did I get the Stone out of the mirror?\"\n\n\"Ah, now, I'm glad you asked me that. It was one of my more brilliant\nideas, and between you and me, that's saying something. You see, only\none who wanted to find the Stone -- find it, but not use it -- would be\nable to get it, otherwise they'd just see themselves making gold or\ndrinking Elixir of Life. My brain surprises even me sometimes.... Now,\nenough questions. I suggest you make a start on these sweets. Ah! Bettie\nBott's Every Flavor Beans! I was unfortunate enough in my youth to come\nacross a vomitflavored one, and since then I'm afraid I've rather lost\nmy liking for them -- but I think I'll be safe with a nice toffee, don't\nyou?\"\n\nHe smiled and popped the golden-brown bean into his mouth. Then he\nchoked and said, \"Alas! Ear wax!\"\n\nMadam Pomfrey, the nurse, was a nice woman, but very strict.\n\n\"Just five minutes,\" Harry pleaded.\n\n\"Absolutely not.\"\n\n\"You let Professor Dumbledore in...\"\n\n\"Well, of course, that was the headmaster, quite different. You need\nrest.\"\n\n\"I am resting, look, lying down and everything. Oh, go on, Madam\nPomfrey...\"\n\n\"Oh, very well,\" she said. \"But five minutes only.\"\n\nAnd she let Ron and Hermione in.\n\n\"Harry!\"\n\nHermione looked ready to fling her arms around him again, but Harry was\nglad she held herself in as his head was still very sore.\n\n\"Oh, Harry, we were sure you were going to -- Dumbledore was so worried\n--\"\n\n\"The whole school's talking about it,\" said Ron. \"What really happened?\"\n\nIt was one of those rare occasions when the true story is even more\nstrange and exciting than the wild rumors. Harry told them everything:\nQuirrell; the mirror; the Stone; and Voldemort. Ron and Hermione were a\nvery good audience; they gasped in all the right places, and when Harry\ntold them what was under Quirrell's turban, Hermione screamed out loud.\n\n\"So the Stone's gone?\" said Ron finally. \"Flamel's just going to die?\"\n\n\"That's what I said, but Dumbledore thinks that -- what was it? -- 'to\nthe well-organized mind, death is but the next great adventure.\n\n\"I always said he was off his rocker,\" said Ron, looking quite impressed\nat how crazy his hero was.\n\n\"So what happened to you two?\" said Harry.\n\n\"Well, I got back all right,\" said Hermione. \"I brought Ron round --\nthat took a while -- and we were dashing up to the owlery to contact\nDumbledore when we met him in the entrance hall -- he already knew -- he\njust said, 'Harry's gone after him, hasn't he?' and hurtled off to the\nthird floor.\"\n\n\"D'you think he meant you to do it?\" said Ron. \"Sending you your\nfather's cloak and everything?\"\n\n\"Well, \" Hermione exploded, \"if he did -- I mean to say that's terrible\n-- you could have been killed.\"\n\n\"No, it isn't,\" said Harry thoughtfully. \"He's a funny man, Dumbledore.\nI think he sort of wanted to give me a chance. I think he knows more or\nless everything that goes on here, you know. I reckon he had a pretty\ngood idea we were going to try, and instead of stopping us, he just\ntaught us enough to help. I don't think it was an accident he let me\nfind out how the mirror worked. It's almost like he thought I had the\nright to face Voldemort if I could....\"\n\n\"Yeah, Dumbledore's off his rocker, all right,\" said Ron proudly.\n\"Listen, you've got to be up for the end-of-year feast tomorrow. The\npoints are all in and Slytherin won, of course -- you missed the last\nQuidditch match, we were steamrollered by Ravenclaw without you -- but\nthe food'll be good.\"\n\nAt that moment, Madam Pomfrey bustled over.\n\n\"You've had nearly fifteen minutes, now OUT\" she said firmly.\n\nAfter a good night's sleep, Harry felt nearly back to normal.\n\nI want to go to the feast,\" he told Madam Pomfrey as she straightened\nhis many candy boxes. I can, can't I?\"\n\n\"Professor Dumbledore says you are to be allowed to go,\" she said\nstiffily, as though"
    }
}
